(function(g){var window=this;'use strict';var Njg=async function(t,p,Q){t.S=g.a8(p,Q)},nP=function(t){t.isActive()||t.start()},uIh=function(t,p){var Q=new g.w3;
Q.languageCode=t.languageCode;Q.languageName=t.languageName;Q.name=t.name;Q.displayName=t.displayName;Q.kind=t.kind;Q.isDefault=!1;Q.X=t.X;Q.isTranslateable=t.isTranslateable;Q.vssId=t.vssId;Q.url=t.url;Q.translationLanguage=p;t.xtags&&(Q.xtags=t.xtags);t.captionId&&(Q.captionId=t.captionId);return Q},Rc=function(t,p){return p?t.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},osE=function(t){return g.C$(t)||t.Y("web_enable_caption_language_preference_stickiness")},z6o=async function(t,p){t=
t+"|"+p;
p=await g.Qw();if(!p)throw g.ZU("gct");return(await g.zw(p)).get("captions",t)},yFz=function(t,p,Q){z6o(t,p).then(e=>{e&&Q(e.trackData,new g.w3(e.metadata))})},NT=function(t){if(!mzn.test(t))throw Error("'"+t+"' is not a valid hex color");
t.length==4&&(t=t.replace($zf,"#$1$1$2$2$3$3"));t=t.toLowerCase();t=parseInt(t.slice(1),16);return[t>>16,t>>8&255,t&255]},X1O=function(){var t={},p="suggest_correction"in g.Db?g.Db.suggest_correction:"Edit caption";
p=p||"";for(let Q in t){let e=()=>String(t[Q]);
p=p.replace(new RegExp("\\$\\{"+Q+"\\}","gi"),e);p=p.replace(new RegExp("\\$"+Q,"gi"),e)}return p},uE=function(){return g.Ag("yt-player-caption-display-settings")},Dze=function(t,p){var Q=g.zn(t.segments,p);
Q>=0||Q<0&&(-Q-1)%2===1||(Q=-Q-1,Q>0&&p-t.segments[Q-1]===1&&Q<t.segments.length&&t.segments[Q]-p===1?(g.pg(t.segments,Q),g.pg(t.segments,Q-1)):Q>0&&p-t.segments[Q-1]===1?t.segments[Q-1]=p:Q<t.segments.length&&t.segments[Q]-p===1?t.segments[Q]=p:(g.NO(t.segments,Q,0,p),g.NO(t.segments,Q+1,0,p)))},Esz=function(t){return t.X&&t.X.L?t.X.L+t.player.jX()<t.player.getCurrentTime():!1},Lky=function(t,p){if(t.policy.xV&&t.player.St()){var Q=g.K9(p,t.policy,{});
Q.set("pot",t.player.St());Q=Q.tq()}else Q=g.K9(p,t.policy,{}).tq();var e={format:"RAW",withCredentials:!0};if(t.policy.TH){e.method="POST";let k=p.K;k&&Object.keys(k).length>0?e.postBody=g.hU(k,g.mF):e.postBody=(0,g.$A)([120,0])}t.L&&(e.responseType="arraybuffer");var J=++t.Sv,S=(0,g.l)();t.S=g.Pb(Q,e,3,100,-1,k=>{k.errorCode==="net.timeout"&&t.player.XU("capnt",{rn:J++})}).then(k=>{if(t.policy.jL&&J%100===1){var w=(0,g.l)();
t.player.XU("caprsp",{rn:J,ms:w-S,kb:(k.xhr.responseText.length/1024).toFixed()})}a:{k=k.xhr;t.UL();if(t.U){var f=!(t.L?k.response:k.responseText)||k.status>=400;if(w=g.nkc(k)){k=g.K9(t.U,t.policy,{});t.U.p$(k,w);Lky(t,t.U);break a}f?t.player.XU("capfail",{status:k.status}):(g.gm("fcb_r",(0,g.l)(),t.player.getVideoData().Md||""),w=t.U.IH[0],f=w.Cx,t.V!=null&&t.C!==f&&(t.L?t.V(k.response,(w.segmentStartTime+t.player.jX())*1E3):t.V(k.responseText,(w.segmentStartTime+t.player.jX())*1E3),t.C=f))}t.U=
null;t.S=null}}).rf(k=>{t.U=null;
t.S=null;t.player.XU("capfail",{rn:J,status:k.xhr?.status})});
t.U=p;Dze(t.K,t.U.IH[0].Cx)},jVe=function(t,p){return p!=null&&p in t.S.X?t.S.X[p]:null},vsm=function(t,p,Q){var e=[];
for(let J in t.S.X){if(!t.S.X.hasOwnProperty(J))continue;let S=t.S.X[J];if(g.Ur(S,Q||null)){let k=S.info.captionTrack;k&&k.languageCode===p&&e.push(S)}}return e.length?e[0]:null},bzg=function(t,p){var Q=[];
for(let J in t.S.X){if(!t.S.X.hasOwnProperty(J))continue;var e=t.S.X[J];if(g.Ur(e,p||null)){let S=e.info.id,k=S,w=`.${S}`,f="",R="";if(e=e.info.captionTrack)S=e.languageCode,k=e.displayName,w=e.vssId,f=e.kind,R=e.id;Q.push(new g.w3({id:J,languageCode:S,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:w,kind:f,captionId:R}))}}return Q},gsh=function(t,p,Q,e){var J=p/360*16;
p>=t&&(t=640,e>Q*1.3&&(t=480),J=Q/t*16);return J},V9E=function(t){var p=1+.25*(t.fontSizeIncrement||0);
if(t.offset===0||t.offset===2)p*=.8;return p},dzE=function(t,p){var Q="vertical-rl";
t.X.IZ===1&&(Q="vertical-lr");g.sj&&(Q=Q==="vertical-lr"?"tb-lr":"tb-rl");g.rI(p,"-o-writing-mode",Q);g.rI(p,"-webkit-writing-mode",Q);g.rI(p,"writing-mode",Q);g.rI(p,"text-orientation","upright");g.M3(p,"ytp-vertical-caption");t.S.params.KF===3&&(g.rI(p,"text-orientation",""),g.rI(p,"transform","rotate(180deg)"))},Gxg=function(t,p){var Q={},e=p.background?p.background:t.X.T1.background;
if(p.backgroundOpacity!=null||p.background){var J=p.backgroundOpacity!=null?p.backgroundOpacity:t.X.T1.backgroundOpacity;e=NT(e);Q.background="rgba("+e[0]+","+e[1]+","+e[2]+","+J+")";t.Zr&&(Q["box-decoration-break"]="clone",Q["border-radius"]=`${t.y3*.25}px`)}if(p.fontSizeIncrement!=null||p.offset!=null)Q["font-size"]=`${t.V3*V9E(p)}px`;t.experiments.OL("enable_player_captions_new_style_defaults")&&(Q["line-height"]="1.375");e=1;J=p.color||t.X.T1.color;if(p.color||p.textOpacity!=null)J=NT(J),e=p.textOpacity==
null?t.X.T1.textOpacity:p.textOpacity,J="rgba("+J[0]+","+J[1]+","+J[2]+","+e+")",Q.color=J,Q.fill=J;var S=p.charEdgeStyle;S===0&&(S=void 0);if(S){J=`rgba(34, 34, 34, ${e})`;let f=`rgba(204, 204, 204, ${e})`;p.QR&&(f=J=p.QR);let R=t.V3/16/2,z=Math.max(R,1);var k=Math.max(2*R,1),w=Math.max(3*R,1);let y=Math.max(5*R,1);e=[];switch(S){case 4:for(;w<=y;w+=R)e.push(`${k}px ${k}px ${w}px ${J}`);break;case 1:k=window.devicePixelRatio>=2?.5:1;for(S=z;S<=w;S+=k)e.push(`${S}px ${S}px ${J}`);break;case 2:e.push(`${z}px ${z}px ${f}`);
e.push(`-${z}px -${z}px ${J}`);break;case 3:for(w=0;w<5;w++)e.push(`0 0 ${k}px ${J}`)}Q["text-shadow"]=e.join(", ")}J="";switch(p.fontFamily){case 1:J='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", serif-monospace, monospace';break;case 2:J='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:J='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", sans-serif-monospace, monospace';break;case 5:J='"Comic Sans MS", Impact, Handlee, fantasy';break;
case 6:J='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:J=g.fp()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:J='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}J&&(Q["font-family"]=J);J=p.offset;J==null&&(J=t.X.T1.offset);switch(J){case 0:Q["vertical-align"]="sub";break;case 2:Q["vertical-align"]="super"}p.fontFamily===7&&(Q["font-variant"]=
"small-caps");p.bold&&(Q["font-weight"]="bold");p.italic&&(Q["font-style"]="italic");p.underline&&(Q["text-decoration"]="underline");p.mH&&(Q.visibility="hidden");p.sF===1&&t.K&&(Q["text-combine-upright"]="all",Q["text-orientation"]="mixed",J=g.BS||g.GT,t.S.params.KF===3?Q.transform=J?"rotate(90deg)":"rotate(180deg)":J&&(Q.transform="rotate(-90deg)"));if(p.textEmphasis===1||p.textEmphasis===2||p.textEmphasis===3||p.textEmphasis===4||p.textEmphasis===5)if(g.BS)Q["font-weight"]="bold";else switch(Q["text-emphasis-style"]=
"filled circle",Q["text-emphasis-color"]="currentcolor",Q["webkit-text-emphasis"]="filled circle",p.textEmphasis){case 4:case 3:Q["text-emphasis-position"]="under left";Q["webkit-text-emphasis-position"]="under left";break;case 5:case 2:Q["text-emphasis-position"]="over right",Q["webkit-text-emphasis-position"]="over right"}return Q},rFg=function(t,p){if(t.GH&&p.length===0)return 0;
t=1;for(let Q=0;Q<p.length;Q++){let e=p[Q];typeof e.text==="string"&&(t+=e.text.split("\n").length-1,e.append||Q===0||t++)}return t},oc=function(t){t=t.split("px");
return t.length>0?(t=Number(t[0]))?t:0:0},M9n=function(t,p,Q){t.TH=t.TH||!!Q;
var e={};Object.assign(e,t.X.T1);Object.assign(e,Q||p.X);Object.assign(e,t.jH.T1);t.Dr&&(e.backgroundOpacity=0);(Q=!t.L)&&Tjy(t);var J=t.Kx&&t.sL&&g.Wz(e,t.sL)?t.Kx:ZzO(t,e),S=typeof p.text==="string",k=S?p.text.split("\n"):[p.text];for(let f=0;f<k.length;f++){var w=f>0||!p.append;let R=k[f];w&&!Q?(Tjy(t),J=ZzO(t,e)):w&&Q&&(Q=!1);R&&(J.appendChild(S?g.ey(R):R),S||R.tagName!=="RUBY"||R.childElementCount!==4||g.BS||!g.Ix(R.children[2],"text-emphasis")||(w=t.K?"padding-right":"padding-top",g.Ix(R.children[2],
"text-emphasis-position")&&(w=t.K?"padding-left":"padding-bottom"),g.U4?g.rI(J,w,"1em"):g.rI(J,w,"0.5em")))}t.sL=e;t.Kx=J;t.Z.push(p)},Tjy=function(t){if(t.L){var p=t.L;
if(t.Zr){var Q=t.X.textAlign;Q===0?(p=p.firstElementChild)&&g.rI(p,{"border-bottom-left-radius":"0"}):Q===1&&(p=p.lastElementChild)&&g.rI(p,{"border-bottom-right-radius":"0"})}}t.L=g.Qp("SPAN");g.rI(t.L,{display:"block"});g.M3(t.L,"caption-visual-line");t.U.appendChild(t.L)},ZzO=function(t,p){var Q=g.Qp("SPAN");
g.rI(Q,{display:"inline-block","white-space":"pre-wrap"});g.rI(Q,Gxg(t,p));Q.classList.add("ytp-caption-segment");t.L.appendChild(Q);t.Zr&&t.U.children.length>1&&(t=t.X.textAlign,t===0?Q.previousElementSibling||g.rI(Q,{"border-top-left-radius":"0"}):t===1&&g.rI(Q,{"border-top-right-radius":"0"}));Q.previousElementSibling&&(g.rI(Q.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.rI(Q,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return Q},
xzT=function(t,p,Q){if(t===255&&p===255||!t&&!p)return{Uu:t,
Xv:p,result:0};t=I2z[t];p=I2z[p];if(t&128){var e;if(e=!(p&128))e=p,e=Q.Qc()&&Q.Xv===e;if(e)return{Uu:t,Xv:p,result:1}}else if(p&128&&1<=t&&t<=31)return{Uu:t,Xv:p,result:2};return{Uu:t,Xv:p,result:3}},q16=function(t,p,Q,e){p===255&&Q===255||!p&&!Q?(++t.U===45&&t.reset(),t.K.S.clear(),t.L.S.clear()):(t.U=0,CPo(t.K,p,Q,e))},OzE=function(t,p){t.X.sort((Q,e)=>{var J=Q.time-e.time;
return J===0?Q.order-e.order:J});
for(let Q of t.X)t.time=Q.time,Q.type===0?q16(t,Q.o_,Q.eA,p):Q.type===1&&t.S&496&&CPo(t.L,Q.o_,Q.eA,p);t.X.length=0},Wkg=function(t,p){switch(t){case 0:return Y16[(p&127)-32];
case 1:return a2f[p&15];case 2:return sVz[p&31];case 3:return Bj6[p&31]}return 0},zQ=function(t,p){if(t.style.type===3){var Q=0,e=0,J=t.L.time+0,S="",k="",w=J;
for(var f=1;f<=15;++f){var R=!1;for(var z=e?e:1;z<=32;++z){var y=t.U[f][z];if(y.X!==0){Q===0&&(Q=f,e=z);R=String.fromCharCode(y.X);var X=y.timestamp;X<J&&(J=X);y.timestamp=w;k&&(S+=k,k="");S+=R;R=!0}if((y.X===0||z===32)&&R){k="\n";break}else if(e&&!R)break}if(Q&&!R)break}S&&p.K(Q,e,J,w,S)}else for(e=Q=0,S=J=t.L.time+0,k=1;k<=15;++k)for(w="",f=1;f<=32;++f)if(z=t.U[k][f],y=z.X,y!==0&&(Q===0&&(Q=k,e=f),R=String.fromCharCode(y),X=z.timestamp,X<=J&&(J=X),w+=R,z.reset()),f===32||y===0)w&&p.K(Q,e,J,S,w),
J=S,w="",e=Q=0},yT=function(t){return t.U[t.row][t.S]},mg=function(t,p,Q){p>=2&&t.S>1&&(--t.S,yT(t).X=0);
var e=yT(t);e.timestamp=t.L.time+0;e.X=Wkg(p,Q);t.S<32&&t.S++},PPe=function(t,p,Q,e){for(let J=0;J<e;J++)for(let S=0;S<=32;S++)t.U[p+J][S].copy(t.U[Q+J][S])},$G=function(t,p,Q){for(let e=0;e<Q;e++)for(let J=0;J<=32;J++)t.U[p+e][J].reset()},Xt=function(t){t.row=t.X>0?t.X:1;
t.S=1;$G(t,0,15)},HzE=function(t){t.style.set(1);
t.X=t.K;t.X.X=0;t.X.style=t.style;t.U.mode=1<<t.X.K},DC=function(t,p,Q){var e=t.S,J=!1;
switch(t.style.get()){case 4:case 1:case 2:t.style.get()===4&&e.X>0||(zQ(e,Q),Xt(t.S),Xt(t.K),e.row=15,e.X=p,J=!0)}t.style.set(3);t.X=e;t.X.style=t.style;t.U.mode=1<<e.K;J?e.S=1:e.X!==p&&(e.X>p?(zQ(e,Q),$G(e,e.row-e.X,p)):e.row<p&&(p=e.X),e.X=p)},KkE=function(t){t.style.set(4);
t.X=t.text;t.X.style=t.style;t.U.mode=1<<t.X.K},CPo=function(t,p,Q,e){t.S.update();
p=xzT(p,Q,t.S);switch(p.result){case 0:return;case 1:case 2:return}var J=p.Uu;p=p.Xv;if(32<=J||!J)t.X.mode&t.X.S&&(Q=J,Q&128&&(Q=127),p&128&&(p=127),t=t.K.X,Q&96&&mg(t,0,Q),p&96&&mg(t,0,p),Q!==0&&p!==0&&t.style.type===3&&zQ(t,e));else if(J&16)a:if(!t.S.matches(J,p)&&(Q=t.S,Q.Uu=J,Q.Xv=p,Q.state=2,Q=J&8?t.C:t.U,t.K=Q,t.X.mode=1<<(t.L<<2)+(Q.L<<1)+(Q.style.type===4?1:0),(t.X.mode|1<<(t.L<<2)+(Q.L<<1)+(Q.style.type!==4?1:0))&t.X.S))if(p&64){e=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(J&7)<<1|p>>5&1];
t=p&16?((p&14)>>1)*4:0;p=Q.X;switch(Q.style.get()){case 4:e=p.row;break;case 3:if(e!==p.row){if(e<p.X&&(e=p.X,e===p.row))break;var S=1+p.row-p.X;let k=1+e-p.X;PPe(p,k,S,p.X);Q=S;J=p.X;k<S?(S=k+J-S,S>0&&(Q+=S,J-=S)):(S=S+J-k,S>0&&(J-=S));$G(p,Q,J)}}p.row=e;p.S=t+1}else switch(J&7){case 1:switch(p&112){case 32:mg(Q.X,0,32);break a;case 48:p===57?(e=Q.X,yT(e).X=0,e.S<32&&e.S++):mg(Q.X,1,p&15)}break;case 2:p&32&&mg(Q.X,2,p&31);break;case 3:p&32&&mg(Q.X,3,p&31);break;case 4:case 5:if(32<=p&&p<=47)switch(p){case 32:HzE(Q);
break;case 33:e=Q.X;e.S>1&&(--e.S,yT(e).X=0);break;case 36:e=Q.X;t=yT(e);for(p=0;p<=15;p++)for(Q=0;Q<=32;Q++)if(e.U[p][Q]===t){for(;Q<=32;Q++)e.U[p][Q].reset();break}break;case 37:DC(Q,2,e);break;case 38:DC(Q,3,e);break;case 39:DC(Q,4,e);break;case 40:mg(Q.X,0,32);break;case 41:e=Q;e.style.set(2);e.X=e.S;e.X.X=0;e.X.style=e.style;e.U.mode=1<<e.X.K;break;case 42:e=Q;t=e.text;t.X=15;t.style.set(4);Xt(t);KkE(e);break;case 43:KkE(Q);break;case 44:t=Q;p=t.S;switch(t.style.get()){case 1:case 2:case 3:zQ(p,
e)}$G(p,0,15);break;case 45:b:{p=Q;t=p.X;switch(p.style.get()){default:case 2:case 1:break b;case 4:if(t.row<15){++t.row;t.S=1;break b}break;case 3:}t.X<2&&(t.X=2,t.row<t.X&&(t.row=t.X));p=t.row-t.X+1;zQ(t,e);PPe(t,p,p+1,t.X-1);$G(t,t.row,1)}break;case 46:$G(Q.K,0,15);break;case 47:t=Q,zQ(t.S,e),t.K.updateTime(t.U.time+0),e=t.K,t.K=t.S,t.S=e,HzE(t)}break;case 7:switch(p){case 33:case 34:case 35:e=Q.X,(e.S+=p&3)>32&&(e.S=32)}}},h6X=function(t,p,Q,e,J,S,k){var w=S[0],f=k[w.getAttribute("p")];
if(f.iQ===1){var R=S[1],z=S[2];S=S[3];w.getAttribute("t");R.getAttribute("t");z.getAttribute("t");S.getAttribute("t");w.getAttribute("p");R.getAttribute("p");S.getAttribute("p");k=k[z.getAttribute("p")];w=l2m(w.textContent,R.textContent,z.textContent,S.textContent,k);return new EW(t,p,J,Q,w,e,f)}switch(f.iQ){case 9:case 10:f.textEmphasis=1;break;case 11:f.textEmphasis=2;break;case 12:f.textEmphasis=3;break;case 13:f.textEmphasis=4;break;case 14:f.textEmphasis=5}return new EW(t,p,J,Q,w.textContent||
"",e,f)},l2m=function(t,p,Q,e,J){var S=g.fp(),k=S?g.Qp("DIV"):g.Qp("RUBY"),w=g.Qp("SPAN");
w.textContent=t;k.appendChild(w);t=S?g.Qp("DIV"):g.Qp("RP");t.textContent=p;k.appendChild(t);p=S?g.Qp("DIV"):g.Qp("RT");p.textContent=Q;k.appendChild(p);Q=J.iQ;if(Q===10||Q===11||Q===12||Q===13||Q===14)if(g.rI(p,"text-emphasis-style","filled circle"),g.rI(p,"text-emphasis-color","currentcolor"),g.rI(p,"webkit-text-emphasis","filled circle"),J.iQ===11||J.iQ===13)g.rI(p,"webkit-text-emphasis-position","under left"),g.rI(p,"text-emphasis-position","under left");Q=!0;if(J.iQ===4||J.iQ===7||J.iQ===12||
J.iQ===14)g.rI(k,"ruby-position","over"),g.rI(k,"-webkit-ruby-position","before");else if(J.iQ===5||J.iQ===6||J.iQ===11||J.iQ===13)g.rI(k,"ruby-position","under"),g.rI(k,"-webkit-ruby-position","after"),Q=!1;J=S?g.Qp("DIV"):g.Qp("RP");J.textContent=e;k.appendChild(J);S&&(e=Q,g.rI(k,{display:"inline-block",position:"relative"}),S=k.firstElementChild.nextElementSibling,g.rI(S,"display","none"),S=S.nextElementSibling,g.rI(S,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.rI(k.lastElementChild,"display","none"),e?(g.rI(k,"padding-top","0.6em"),g.rI(S,"top","0")):(g.rI(k,"padding-bottom","0.6em"),g.rI(S,"bottom","0")));return k},Fkm=function(t){var p="_"+LP++;
return new jL(0,0x8000000000000,0,p,t)},vG=function(t,p){t=t.getAttribute(p);
if(t!=null)return Number(t)},bE=function(t,p){t=t.getAttribute(p);
if(t!=null)return t==="1"},gW=function(t,p){t=vG(t,p);
return t!==void 0?t:null},dW=function(t,p){t=t.getAttribute(p);
if(t!=null)return VT.test(t),t},AFz=function(t,p){var Q={},e=p.getAttribute("ws");
Object.assign(Q,e?t.D[e]:t.K);t=gW(p,"mh");t!=null&&(Q.XA=t);t=gW(p,"ju");t!=null&&(Q.textAlign=t);t=gW(p,"pd");t!=null&&(Q.KF=t);t=gW(p,"sd");t!=null&&(Q.IZ=t);t=dW(p,"wfc");t!=null&&(Q.windowColor=t);p=vG(p,"wfo");p!==void 0&&(Q.windowOpacity=p/255);return Q},UzX=function(t,p){var Q={},e=p.getAttribute("wp");
e&&Object.assign(Q,t.V[e]);t=gW(p,"ap");t!=null&&(Q.zG=t);t=vG(p,"cc");t!=null&&(Q.q3=t);t=vG(p,"ah");t!=null&&(Q.Jn=t);t=vG(p,"rc");t!=null&&(Q.BO=t);p=vG(p,"av");p!=null&&(Q.hz=p);return Q},cFz=function(t,p,Q,e){var J={};
Object.assign(J,UzX(t,p));Object.assign(J,AFz(t,p));e?g.Wz(J,t.K)?(e=t.L,J=t.K):e="_"+LP++:e=p.getAttribute("id")||"_"+LP++;t=vG(p,"t")+Q;p=vG(p,"d")||0x8000000000000;if(J.KF===2||J.KF===3)Q=J.BO,J.BO=J.q3,J.q3=Q;return new jL(t,p,0,e,J)},GQ=function(t){t=g.jP(Math.round(t),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-t.length)+t},tj6=function(t,p,Q,e,J){e===0&&(e=0x8000000000000);
var S={};p.wpWinPosId&&Object.assign(S,t.K.get(p.wpWinPosId));p.wsWinStyleId&&Object.assign(S,t.L.get(p.wsWinStyleId));t=p.rcRowCount;t!==void 0&&(S.BO=t);p=p.ccColCount;p!==void 0&&(S.q3=p);if(S.KF===2||S.KF===3)p=S.BO,S.BO=S.q3,S.q3=p;return new jL(Q,e,0,J,S)},rW=function(t){var p=t.byteOffset;
t.byteOffset+=1;return t.X.getUint8(p)},TQ=function(t){var p=t.byteOffset;
t.byteOffset+=4;return t.X.getUint32(p)},QLE=function(t){if(typeof t==="string")return!1;
t=new iZX(t,0);return pwy(t)},pwy=function(t){if(!(t.byteOffset<t.X.byteLength)||TQ(t)!==1380139777)return!1;
t.version=rW(t);if(t.version>1)return!1;rW(t);rW(t);rW(t);return!0},e1y=function(t,p){if(!p)return"";
t.K&&t.S.params.IZ!==1&&(p*=-1);return`translate${t.K?"X":"Y"}(${p}px)`},Jro=function(t){t.EL=Array.from(t.element.getElementsByClassName("caption-visual-line"));
for(var p=t.S.params.BO,Q=0,e=0,J=t.EL.length-1;Q<p&&J>-1;){var S=t.EL[J];e+=t.K?S.offsetWidth:S.offsetHeight;Q++;J--}t.Ph=e;p=Math;Q=p.max;isNaN(t.gm)&&((e=t.X.q3)?(J=g.Qp("SPAN"),g.nj(J,"\u2013".repeat(e)),g.rI(J,Gxg(t,t.X.T1)),t.U.appendChild(J),t.gm=J.offsetWidth,t.U.removeChild(J)):t.gm=0);e=t.U;p=Q.call(p,t.gm,t.B0,(t.K?e.offsetHeight:e.offsetWidth)+1);t.SX&&(p=Math.min(p,t.maxWidth));t.Sv=p},Sj6=function(t,p){Jro(t);
var Q=t.EL.reduce((e,J)=>(t.K?J.offsetWidth:J.offsetHeight)+e,0);
Q=t.Ph-Q;if(Q!==t.aL){let e=Q>0&&t.aL===0,J=Q<t.aL;p||isNaN(Q)||e||!J||(g.M3(t.element,"ytp-rollup-mode"),t.O(t.element,"transitionend",t.H0));g.rI(t.U,"transform",e1y(t,Q));t.aL=Q}Jro(t)},wwh=function(t,p,Q,e){var {formatId:J,
Cx:S,startTimeMs:k,durationMs:w}=t.WI(p),f={formatId:J,startTimeMs:k,durationMs:w,Zc:S,AZ:S},R=kLy(t.VA,f.startTimeMs),z=R>=0?t.VA[R]:null,y=z?z.startTimeMs+z.durationMs:0,X=f.startTimeMs+f.durationMs;!z||f.startTimeMs-y>t.K?t.VA.splice(R+1,0,f):(z.durationMs=Math.max(y,X)-z.startTimeMs,z.AZ=Math.max(z.AZ,f.AZ));e(t.VA);e=g.tL(p);t=t.L;e=e.buffer.slice(e.byteOffset,e.byteLength+e.byteOffset);p=p.info.K;t.Sv?t.V==null?g.be(t.logger,350058965,"Null loaded track meta data at captions data received"):
Q.WC(e,t.V,p*1E3):g.be(t.logger,350058965,"Null Representation at captions data received")},R1z=function(t,p){t.S=(Q,e)=>{if(t.J.j().experiments.OL("html5_sabr_live_support_subfragmented_captions"))(t.X?t.X=t.X.merge(Q):(t.X=Q,f4f(t.X)),t.X)?Q.info.Wp&&(n9o(t.X),wwh(t,t.X,p,e),t.X=null):g.be(t.logger,350058965,"Empty slice");
else if(Q.info.Wp){var J=Q;if(t.L$.length>0){for(J=t.L$.shift();t.L$.length>0;)J=J?.merge(t.L$.shift());J=J?.merge(Q)}J?(f4f(J),n9o(J),wwh(t,J,p,e)):g.be(t.logger,350058965,"Empty slice")}else t.L$.push(Q)};
t.J.addEventListener("sabrCaptionsDataLoaded",t.S)},kLy=function(t,p){t=g.zn(t,{startTimeMs:p},(Q,e)=>Q.startTimeMs-e.startTimeMs);
return t>=0?t:-t-2},f4f=function(t){try{var p=g.e1(t)*1E3}catch(Q){p=t.info.segmentStartTime*1E3}p<0&&(p=t.info.segmentStartTime*1E3);
t.info.segmentStartTime=p/1E3;t.info.K=p/1E3},n9o=function(t){try{var p=g.i4h(t)*1E3}catch(Q){p=t.info.U*1E3}p<0&&(p=t.info.U*1E3);
t.info.U=p/1E3;t.info.Z=p/1E3},Nqy=function(t,p){if(!g.M17(t)||t.X!=null&&g.AQ(p,t.X)&&t.X.X.rawcc!=null)return!1;
p=!!t.X&&t.X.isManifestless&&Object.values(t.X.X).some(Q=>g.Ur(Q,"386"));
t=!!t.X&&!t.X.isManifestless&&g.GCC(t.X);return p||t},u8n=function(t,p,Q){var e=[];
for(let J in t.S.X){if(!t.S.X.hasOwnProperty(J))continue;let S=t.S.X[J];if(g.Ur(S,Q||null)){let k=S.info.captionTrack;k&&k.languageCode===p&&e.push(S)}}return e.length?e[0]:null},o9m=function(t,p){var Q=[];
for(let J in t.S.X){if(!t.S.X.hasOwnProperty(J))continue;var e=t.S.X[J];if(g.Ur(e,p||null)){let S=e.info.id,k=S,w=`.${S}`,f="",R="";if(e=e.info.captionTrack)S=e.languageCode,k=e.displayName,w=e.vssId,f=e.kind,R=e.id;Q.push(new g.w3({id:J,languageCode:S,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:w,kind:f,captionId:R}))}}return Q},yrh=function(t){var p=z1g.length;
if(t.byteLength<p)return!1;t=new Uint8Array(t,0,p);for(let Q=0;Q<p;Q++)if(z1g[Q]!==t[Q])return!1;return!0},ZC=function(t){t=t.split(":");
var p=0;for(let Q of t)p=p*60+Number(Q);return p*1E3},m3o=function(t,p,Q,e){e=Object.assign({XA:0},e);
return new jL(t,p,Q,"_"+LP++,e)},$3X=function(t,p,Q,e,J,S,k,w,f){switch(k.tagName){case "b":w.bold=!0;
break;case "i":w.italic=!0;break;case "u":w.underline=!0}for(let z=0;z<k.childNodes.length;z++){var R=k.childNodes[z];if(R.nodeType===3)R=new EW(p,Q,e,J.id,R.nodeValue,S||z>0,g.Yf(w)?void 0:w),f.push(R),J.X.push(R);else{let y={};Object.assign(y,w);$3X(t,p,Q,e,J,!0,R,y,f)}}},D3e=function(t,p,Q){if(typeof p==="string"||QLE(p))return[{trackData:p,
hi:Q}];if(typeof p==="string"&&p.substring(0,6)==="WEBVTT"||typeof p!=="string"&&yrh(p))return[{trackData:p,hi:Q}];var e=new DataView(p);if(e.byteLength<=8||e.getUint32(4)!==1718909296)return[];var J=g.frf(e);if(t.Os&&J){var S=g.Hd(J),k=g.Kc(J);J=J.segmentNumber;S&&J&&t.Os.fQ(J,S,k)}t=g.em(e,1835295092);if(!t||!t.length||!t[0].size)return[];S=[];for(k=0;k<t.length;k++)J=t[k],J=new Uint8Array(p,J.dataOffset,J.size-(J.dataOffset-J.offset)),J=g.Tp(J),S.push({trackData:J,hi:Q+k*1E3});Xw6(e,S,Q);return S=
S.filter(w=>!!w.trackData)},LYf=function(t,p,Q){t.X||(t.X=new E9n);
t=t.X.U(p,Q);Math.random()<.01&&g.Lh(Error("Deprecated subtitles format in web player: WebVTT"));return t},Xw6=function(t,p,Q){var e=g.Uz(t,0,1836476516),J=9E4;
e&&(J=g.cd(e)||9E4);e=0;var S=g.em(t,1836019558);for(let w=0;w<S.length;w++){var k=S[w];w<p.length&&(k=g.Uz(t,k.dataOffset,1953653094))&&(k=g.Uz(t,k.dataOffset,1952867444))&&(k=g.Qy(k)/J*1E3,w===0&&(e=k),p[w].hi=k-e+Q||Q*w*1E3)}},jLm=function(t){var p={};
if(t=g.Nw(t))p.lang=t,g.jA3.test(t)&&(p.KF=1);return p},MT=function(t){return t.U==="HLS"&&t.Es?!0:t.Kx&&t.Es&&t.U!=="LIVE"&&t.U!=="SABR_LIVE"},v9f=function(t){return!t.K&&t.Kx&&t.Dr&&(t.U==="LIVE"||t.U==="SABR_LIVE")},Ic=function(t,p,Q=!1){var e=t.Hh.Y("enable_player_captions_new_style_defaults")?bZo:g9E,J=e.T1;
t.L={};Object.assign(t.L,e);t.L.T1={};Object.assign(t.L.T1,J);t.C={T1:{}};var S=p.backgroundOverride?t.C:t.L,k=p.background||J.background;VT.test(k);S.T1.background=k;S=p.colorOverride?t.C:t.L;k=p.color||J.color;VT.test(k);S.T1.color=k;S=p.windowColorOverride?t.C:t.L;k=p.windowColor||e.windowColor;VT.test(k);S.windowColor=k;S=p.backgroundOpacityOverride?t.C:t.L;k=p.backgroundOpacity;k==null&&(k=J.backgroundOpacity);S.T1.backgroundOpacity=k;S=p.fontSizeIncrementOverride?t.C:t.L;k=p.fontSizeIncrement;
k==null&&(k=J.fontSizeIncrement);S.T1.fontSizeIncrement=k;k=p.fontStyleOverride?t.C:t.L;S=p.fontStyle;S==null&&(S=J.bold&&J.italic?3:J.bold?1:J.italic?2:0);k=k.T1;switch(S){case 1:k.bold=!0;delete k.italic;break;case 2:delete k.bold;k.italic=!0;break;case 3:k.bold=!0;k.italic=!0;break;default:delete k.bold,delete k.italic}S=p.textOpacityOverride?t.C:t.L;k=p.textOpacity;k==null&&(k=J.textOpacity);S.T1.textOpacity=k;S=p.windowOpacityOverride?t.C:t.L;k=p.windowOpacity;k==null&&(k=e.windowOpacity);S.windowOpacity=
k;e=p.charEdgeStyleOverride?t.C:t.L;S=p.charEdgeStyle;S==null&&(S=J.charEdgeStyle);e.T1.charEdgeStyle=S;e=p.fontFamilyOverride?t.C:t.L;S=p.fontFamily;S==null&&(S=J.fontFamily);e.T1.fontFamily=S;t.loaded&&t.SX();Q&&g.FC("yt-player-caption-display-settings",p,2592E3)},xG=function(t,p,Q){p&&!t.bV?(p=Fkm({KF:0,
lang:"en-GB"}),t.bV=[p,new EW(p.start,p.end-p.start,0,p.id,Q??"Captions look like this")],t.player.kq(t.bV)):!p&&t.bV&&(Vjg(t,t.bV),t.bV=null)},GLg=function(t){if(t.Hh.Y("enable_player_captions_persistence_state_machine")){var p=g.Ag("yt-player-caption-persistence");
if(p==null){let Q=g.J7().iV(65);if(Q===!0)p=!1;else{let e=g.C$(t.Hh)?CP(t):d3m(t);e!=null?p=!!e:Q===!1&&(p=!0)}p!==void 0&&qT(t,p)}return p}},CP=function(t){if(!t.J.isInline())return g.Ag("yt-player-sticky-caption")},d3m=function(t){if(!t.storage)return null;
try{var p=t.storage.get("module-enabled")}catch(Q){t.storage.remove("module-enabled")}return p},OW=function(t){if(t.Hh.Y("enable_player_captions_persistence_state_machine"))return GLg(t);
var p=void 0,Q=g.J7().iV(65);if(g.C$(t.Hh)&&Q!=null){if(CP(t)!=null)return!1;p=!Q}return p},rrz=function(t){if(t.Hh.CZ===1||t.videoData.jt===1||g.QL(t.videoData,"yt:cc")==="alwayson")return!0;
if(t.videoData.captionTracks.length)var p=t.getAudioTrack().S;if(t.Hh.Y("enable_player_captions_persistence_state_machine")){var Q=GLg(t);if(Q!==void 0)return!!Q}else if(t.Hh.CZ===2&&(g.C$(t.Hh)?Q=CP(t):Q=d3m(t),Q!=null))return!!Q;Q=Rc(t.player.getAudioTrack(),g.C$(t.Hh));var e=g.QL(t.videoData,"yt:cc");if(OW(t)===void 0){if(Q==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return e?e==="on":!0;if(Q==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return e==="on"}else return e==="on";return p==="ON"||g.QL(t.videoData,
"yt:cc")==="on"},YG=function(t,p=!1){if(t.S&&!p||!t.videoData.captionTracks.length)return!1;
t=t.getAudioTrack();return!!t.X||t.S==="FORCED_ON"},Tqz=function(t,p){if(t.S){var Q=t.J.ot().Us().textTracks,e=null;
t.U==="HLS"?e=t.S.getId():e=t.S.toString();for(let S=0;S<Q.length;S++){var J=Q[S];J.id===e&&(p?J.mode!=="showing"&&(J.mode="showing",J=t.S,t.Gh(J,!!J,ac(t)?"g":t.Z?"m":"s")):J.mode==="showing"&&(J.mode="disabled"))}}},ac=function(t){var p=sW(t);
return!!p&&t.S===p},ZZT=function(t,p){if(t.U==="HLS")return!1;
g.o3(t.videoData)&&(p=!0);p||(p=t.U==="TTS"?!1:t.U==="INNERTUBE"?!1:!0);return p||t.Hh.Y("web_watch_disable_account_level_captions_settings")&&g.C$(t.Hh)?!0:!!g.J7().iV(66)},sW=function(t){return t.D&&t.D.X},BG=function(t,p){if(!t.X)return null;
if(t.D&&t.D.K)return t.D.K;p=ZZT(t,p);p=g.dy(t.X.X,p);var Q=null;if(osE(t.Hh)){var e=t.J.isInline()?void 0:g.Ag("yt-player-caption-sticky-language");var J=[e,t.videoData.captionsLanguagePreference,t.Hh.captionsLanguagePreference,g.QL(t.videoData,"yt:cc_default_lang")];let w=!1;for(let f=0;f<J.length;f++){let R=J[f];if(R){w=!0;for(var S=0;S<p.length;S++)if(g.Nw(p[S])===R)return p[S];for(S=0;S<p.length;S++)if(g.Nw(p[S]).split("-")[0]===R.split("-")[0])return p[S]}}if(w&&t.X&&(J=t.X.D,J.length))for(var k of J)if(k.languageCode===
e){Q=k;break}}else for(k=[t.videoData.captionsLanguagePreference,t.Hh.captionsLanguagePreference,g.QL(t.videoData,"yt:cc_default_lang")],e=0;e<k.length;e++)for(J=0;J<p.length;J++)if(g.Nw(p[J])===k[e])return p[J];k=null;t.D&&t.D.U&&(k=t.D.U);k||(k=p.find(w=>w.isDefault)||null);
k||(k=p[0]||sW(t));k&&Q&&g.Nw(k).split("-")[0]!==Q.languageCode.split("-")[0]&&(k=uIh(k,Q));return k},Mjz=function(t,p){var Q=g.dy(t.X.X,!0),e=[];
for(let J=0;J<Q.length;J++){let S=Q[J],k=g.Qp("TRACK");k.setAttribute("kind","subtitles");k.setAttribute("label",g.nc(S));k.setAttribute("srclang",g.Nw(S));k.setAttribute("id",S.toString());t.Ph||k.setAttribute("src",t.X.C(S,"vtt"));S===p&&k.setAttribute("default","1");e.push(k)}p=t.J.ot();p.Sv(e);e=p.Us();t.Dr&&t.EL.O(e.textTracks,"change",t.AT)},KP=function(t,p,Q){t.loaded&&t.unload();
Q!=null&&(t.Z=Q,t.Z&&(t.Hh.Y("enable_player_captions_persistence_state_machine")?qT(t,!!p):g.C$(t.Hh)?WG(t,!!p):PG(t,!!p)));p!==null||YG(t,!0)||t.Gh(p,!!p,t.Z?"m":"s");t.S=p;YG(t)&&(t.S=sW(t));HG(t,t.S??void 0);t.load()},qT=function(t,p){t.Hh.Y("enable_player_captions_persistence_state_machine")&&g.FC("yt-player-caption-persistence",p,3122064E3)},WG=function(t,p){t.J.isInline()||g.FC("yt-player-sticky-caption",p,2592E3)},PG=function(t,p){if(t.storage)try{t.storage.set("module-enabled",p)}catch(Q){}},
HG=function(t,p){t.Hh.Y("html5_modify_caption_vss_logging")&&(t.videoData.TP=p)},x3n=function(t,p){var Q=t.IL[p.id];
Q&&Q.S!==p&&(Q.dispose(),delete t.IL[p.id],Q=null);Q||(Q=I4h(t,p))&&(t.IL[p.id]=Q)},C2e=function(t,p){var Q=p.windowId;
t.Zr[Q]||(t.Zr[Q]=[]);t.Zr[Q].push(p)},I4h=function(t,p){var Q=qjh(t);
if(!Q)return null;var e=t.S?g.Nw(t.S):null;e&&g.jA3.test(e)&&(p.params.KF=1);var J=t.GH.getPlayerSize();e=J.height*t.Sv.height;J=J.width*t.Sv.width;t.Hh.playerStyle!=="google-live"||t.L.isDefault||Object.assign(p.params,t.L);switch(p.params.XA!=null?p.params.XA:p.X.length>1?1:0){case 1:return new OZm(p,t.L,t.C,Q.width,Q.height,J,e,t.Hh.experiments,t.y3.bind(t),t.J);case 2:return new Yjz(p,t.L,t.C,Q.width,Q.height,J,e,t.Hh.experiments,t.y3.bind(t),t.J);default:return new lE(p,t.L,t.C,Q.width,Q.height,
J,e,t.Hh.experiments,t.y3.bind(t),t.J)}},qjh=function(t){var p=t.GH.getVideoContentRect(!0).height,Q=t.GH.getVideoContentRect(!0).width;
if(!p||!Q)return null;p*=t.Sv.height;Q*=t.Sv.width;return{width:Q,height:p}},Vjg=function(t,p){t.player.gT(p);
for(let Q of p)g.Qm(t.gm,Q);nP(t.TH)},a4m=function(t,p){if(!t.X)return{};
if(p){g.Yf(p)||t.fd(p.vss_id,"m");if(t.K&&t.U!=="HLS"||!g.jh(p))return;if(g.Yf(p)){KP(t,null,!0);return}let e;var Q=g.dy(t.X.X,!0);for(let J=0;J<Q.length;J++){let S=Q[J];S.languageCode!==p.languageCode||e&&(S.languageName!==p.languageName||(S.captionId||"")!==(p.captionId||"")||g.nc(S)!==p.displayName)||(e=p.translationLanguage?uIh(S,p.translationLanguage):S)}t.aV(p.position);!e||e===t.S&&t.loaded||(p=g.pc(),Q=g.Nw(e),p.length&&Q===p[p.length-1]||(p.push(Q),g.FC("yt-player-caption-language-preferences",
p)),osE(t.Hh)&&!t.J.isInline()&&g.FC("yt-player-caption-sticky-language",Q,2592E3),KP(t,e,!0))}else return t.loaded&&t.S&&!ac(t)?g.R2(t.S):{};return""};
g.UB.prototype.fQ=g.eh(67,function(t,p,Q){this.S.set(t,{MB:p,nI:Q})});
g.cg.prototype.fQ=g.eh(66,function(t,p,Q){this.Sv.fQ(t,p,Q)});
g.q4.prototype.Ph=g.eh(65,function(){return!1});
g.q4.prototype.K=g.eh(64,function(){});
g.OB.prototype.K=g.eh(63,function(t,p,Q){this.UL();p=this.C(t,p);var e=this.Y7.j().Y("html5_report_captions_ctmp_qoe"),J=(0,g.l)();this.U();Njg(this,p,{format:"RAW",onSuccess:S=>{this.S=null;if(e){var k=(S.responseText.length/1024).toFixed();let w=(0,g.l)();this.videoData.XU("capresp",{ms:w-J,kb:k})}k=S.getResponseHeader&&S.getResponseHeader("Content-Length")?Number(S.getResponseHeader("Content-Length")):0;Q.WC(S.responseText,t,void 0,void 0,k)},
onError:e?S=>{this.videoData.XU("capfail",{status:S?.status??0})}:void 0,
withCredentials:!0})});
g.YY.prototype.K=g.eh(62,function(t,p,Q){this.UL();p=this.C(t,p);this.U();this.S=g.a8(p,{format:"RAW",onSuccess:e=>{this.S=null;var J=e.getResponseHeader&&e.getResponseHeader("Content-Length")?Number(e.getResponseHeader("Content-Length")):0;Q.WC(e.responseText,t,void 0,void 0,J)},
withCredentials:!0})});
g.Ru.prototype.V=g.eh(61,function(){this.mediaElement.V()});
g.k8.prototype.V=g.eh(60,function(){var t=g.BL(document,"track",void 0,this.X);for(let p=0;p<t.length;p++)g.wI(t[p])});
g.Ru.prototype.aL=g.eh(59,function(){return this.mediaElement.aL()});
g.k8.prototype.aL=g.eh(58,function(){return!(!this.X.textTracks||!this.X.textTracks.addEventListener)});
g.Ru.prototype.sL=g.eh(57,function(){return this.mediaElement.sL()});
g.k8.prototype.sL=g.eh(56,function(){return!!this.X.textTracks});
g.Ru.prototype.Sv=g.eh(55,function(t){this.mediaElement.Sv(t)});
g.k8.prototype.Sv=g.eh(54,function(t){for(let p=0;p<t.length;p++)this.X.appendChild(t[p])});
g.N4.prototype.fd=g.eh(40,function(t,p){this.app.Ar().fd(t,p)});
g.Ih.prototype.fd=g.eh(39,function(t,p){this.G.fd(t,p)});
g.Go.prototype.fd=g.eh(38,function(t,p){t=[t,p];g.HJ(this,g.hO(this.provider),"cfi",t)});
g.To.prototype.fd=g.eh(37,function(t,p){this.qoe&&this.qoe.fd(t,p)});
g.ah.prototype.fd=g.eh(36,function(t,p){this.tT.fd(t,p)});
g.lw.prototype.fd=g.eh(35,function(){});
g.Mh.prototype.fd=g.eh(34,function(t,p){g.n6(this,37,[t,p])});
g.N4.prototype.Gh=g.eh(33,function(t,p,Q){this.app.Ar().Gh(t,p,Q)});
g.Ih.prototype.Gh=g.eh(32,function(t,p,Q){this.G.Gh(t,p,Q)});
g.Go.prototype.Gh=g.eh(31,function(t,p,Q){if(this.Kx!==t||this.Es!==p)p=p==="rawcc"?"":p,Q=[t,p,this.Kx,Q],g.HJ(this,g.hO(this.provider),"cfs",Q),this.Kx=t,this.Es=p});
g.To.prototype.Gh=g.eh(30,function(t,p,Q){this.qoe&&this.qoe.Gh(t,p,Q)});
g.ah.prototype.Gh=g.eh(29,function(t,p,Q){this.tT.Gh(t,p,Q)});
g.lw.prototype.Gh=g.eh(28,function(){});
g.Mh.prototype.Gh=g.eh(27,function(t,p,Q){g.n6(this,36,[t,p,Q])});
g.Uv.prototype.J_=g.eh(9,function(t){return(t=this.U(t))?t.X:0});
g.iw.prototype.J_=g.eh(8,function(){return 0});
var $zf=/#(.)(.)(.)/,mzn=/^#(?:[0-9a-f]{3}){1,2}$/i,sLn={en:"English"},BqT=class extends g.q4{constructor(t){super(t);this.S=new Set}L(t){var p=this.Y7.ot();if(p&&p.Us()){p=p.Us().textTracks;for(let Q of p)Q.kind==="subtitles"&&!this.S.has(Q.language)&&Q.language&&(g.FO(this.X,new g.w3({languageCode:Q.language,languageName:Q.language,kind:Q.kind,id:Q.id,displayName:sLn[Q.label]||Q.label,vss_id:`.${Q.language}`})),this.S.add(Q.language))}g.dy(this.X).length>0&&t.AE()}},WYh=class{constructor(){this.segments=
[]}contains(t){t=g.zn(this.segments,t);return t>=0||t<0&&(-t-1)%2===1}length(){return this.segments.length/2}},P2g=class extends g.Xa{constructor(t,p,Q,e,J,S){super();this.policy=t;this.player=p;this.mX=Q;this.V=e;this.L=J;this.Ph=S;this.K=new WYh;this.C=-1;this.S=this.U=this.X=null;this.Sv=0;this.Z=new g.gq(this.bV,1E3,this);this.events=new g.u_(this);g.C(this,this.Z);g.C(this,this.events);this.events.O(p,"SEEK_COMPLETE",this.D);this.D();this.bV()}qQ(){super.qQ();this.S&&this.S.cancel()}D(){this.seekTo(this.player.getCurrentTime())}seekTo(t){t-=
this.player.jX();var p=this.X;this.X=g.af(this.mX.Z(t).IH);p!==this.X&&this.Ph&&this.Ph()}reset(){this.K=new WYh;this.C=-1;this.S&&(this.S.cancel(),this.S=null)}bV(){this.UL();var t;if(t=this.X!=null)t=this.X,t=t.mX.K(t);if(t&&!this.S&&!(this.X&&this.X.segmentStartTime-this.player.getCurrentTime()>30)){t=this.X;t=t.mX.Kx(t);let J=t.IH[0];if(this.player.getVideoData().enableServerStitchedDai){var p=this.player.Rp();if(p){var Q=J.mX.info.id;let S=J.Cx;var e=t.IH[0].K;if(this.policy.TH){if(p=g.QiC(p,
e,S,Q,3))t.K=p}else if(Q=p.kC(e,S,Q,3))if(e=2,p.zY.has(S)?e=0:g.ZI(p,S)&&(e=1),p=e,p===0)Q&&(t.X=new g.MG(Q));else if(p===2){this.Z.start();Esz(this)&&this.seekTo(this.player.getCurrentTime());return}}}J.mX.index.wr(J.Cx)?(this.K.contains(t.IH[0].Cx)||Lky(this,t),this.X=g.af(t.IH)):Esz(this)&&this.seekTo(this.player.getCurrentTime())}this.Z.start()}},HZh=class extends g.q4{constructor(t,p){super(p);this.S=t;this.J=p;this.V=null;this.bV=!1;this.logger=new g.vR("caps");this.Sv=g.AQ(this.J,this.S)}K(t,
p,Q){this.U();p=jVe(this,t.getId());p||(p=t.languageCode,p=this.S.isManifestless?vsm(this,p,"386"):vsm(this,p));if(p){var e=(p.index.J_(p.index.b7())-p.index.getStartTime(p.index.b7()))*1E3,J=new g.BDh(this.J.j());this.V=new P2g(J,this.J,p,(S,k)=>{Q.WC(S,t,k,e)},this.Sv||g.WR(p.info),()=>{this.V&&this.V.reset();
this.bV=!0})}}Ph(){var t=this.bV;
this.bV=!1;return t}L(t){var p=this.J.j().Y("html5_fallback_if_rawcc_missing");var Q=this.S.X.rawcc!=null;if(!this.Sv||!Q&&p)p=this.S.isManifestless?bzg(this,"386"):bzg(this);else{if(!Q){g.be(this.logger,386248249,"rawcc used but unavailable");return}p=[new g.w3({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.w3({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let e of p)g.FO(this.X,
e);t.AE()}U(){this.V&&(this.V.dispose(),this.V=null)}C(){return""}},VT=/^#(?:[0-9a-f]{3}){1,2}$/i;var KYX=["left","right","center","justify"];var EW=class extends g.wN{constructor(t,p,Q,e,J,S=!1,k=null){super(t,t+p,{priority:Q,namespace:"captions"});this.windowId=e;this.text=J;this.append=S;this.X=k}toString(){return super.toString()}};var lE=class extends g.CR{constructor(t,p,Q,e,J,S,k,w,f,R){var z=R.isInline()&&!0,y={};Object.assign(y,p);Object.assign(y,t.params);Object.assign(y,Q);var X={};Object.assign(X,p.T1);t.params.T1&&Object.assign(X,t.params.T1);Object.assign(X,Q.T1);z&&(X.background&&(y.windowColor=X.background),y.windowOpacity=.6,X.backgroundOpacity=0);y.T1=X;var E=y.KF===1,b=[{W:"span",B:"captions-text",N:{style:"word-wrap: normal; display: block;"}}],M=w.OL("caption_edit_on_hover")&&R.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
M&&b.unshift({W:"button",B:"caption-edit",N:{tabindex:"0","aria-label":X1O()},A:[{W:"svg",N:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},A:[{W:"path",N:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({W:"div",B:"caption-window",N:{id:`caption-window-${t.id}`,dir:E?"rtl":"ltr",tabindex:"0",lang:y.lang},A:b});this.experiments=
w;this.Z=[];this.TH=!1;this.S=t;this.sL=this.Kx=null;this.IQ=S;this.d9=k;this.L=null;this.maxWidth=S*.96;this.maxHeight=k*.96;this.X=y;this.jH=Q;this.IL=p;this.U=this.wm("captions-text");t=this.U.style;this.Zr=w.OL("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in t||"WebkitBoxDecorationBreak"in t);this.V3=gsh(e,J,S,k);this.hZ=f;M&&(this.C=this.wm("caption-edit"),this.O(this.C,"click",()=>{this.hZ()}));
this.type=0;this.y3=this.V3*V9E(X);this.Dr=z;this.GH=w.OL("enable_centered_caption_for_tvfilm_video")&&R.getVideoData().isTvfilmVideo;this.D=R.j().MQ().X.iV(g.s5h);this.SX=R.j().MQ().X.iV(g.B0h);e=new g.Z_(this.element,!0);g.C(this,e);e.subscribe("dragstart",this.pV,this);e.subscribe("dragmove",this.bX,this);e.subscribe("dragend",this.eH,this);this.Fd=this.Es=this.aH=this.RH=0;e="";this.X.windowOpacity&&(e=NT(this.X.windowColor),e="rgba("+e[0]+","+e[1]+","+e[2]+","+this.X.windowOpacity+")");J={"background-color":e,
display:this.X.isVisible===!1?"none":"","text-align":KYX[this.X.textAlign]};this.Zr&&(J["border-radius"]=e?`${this.y3*.25}px`:"");(this.K=this.S.params.KF===2||this.S.params.KF===3)&&dzE(this,this.element);g.rI(this.element,J);z&&this.element.parentElement?.style.setProperty("--caption-window-color",e);switch(this.X.zG){case 0:case 1:case 2:g.M3(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.M3(this.element,"ytp-caption-window-bottom")}}pV(t,p){this.Es=t;this.Fd=p;var Q=g.PP(this.element,
this.element.parentElement);this.RH=t-Q.x;this.aH=p-Q.y}bX(t,p){if(t!==this.Es||p!==this.Fd){g.Z4(this.element,"ytp-dragging")||g.M3(this.element,"ytp-dragging");var Q=g.Kj(this.element);t=t-this.RH-.02*this.IQ;var e=p-this.aH-.02*this.d9,J=(t+Q.width/2)/this.maxWidth*3;J=Math.floor(g.jP(J,0,2));var S=(e+Q.height/2)/this.maxHeight*3;S=Math.floor(g.jP(S,0,2));p=J+S*3;t=(t+J/2*Q.width)/this.maxWidth;t=g.jP(t,0,1)*100;Q=(e+S/2*Q.height)/this.maxHeight;Q=g.jP(Q,0,1)*100;this.S.params.zG=p;this.S.params.hz=
Q;this.S.params.Jn=t;this.S.params.isDefault=!1;this.X.zG=p;this.X.hz=Q;this.X.Jn=t;this.X.isDefault=!1;this.IL.zG=p;this.IL.hz=Q;this.IL.Jn=t;this.IL.isDefault=!1;this.PT()}}eH(){g.x9(this.element,"ytp-dragging")}PT(){this.V(this.Z)}V(t){var p=this.Dr?0:Math.min(this.MX(),this.maxWidth),Q=this.YY(),e=this.Dr;if(e){var J=getComputedStyle(this.U.parentNode);J=oc(J.borderLeftWidth)+oc(J.borderRightWidth)+oc(J.paddingLeft)+oc(J.paddingRight)}else J=0;var S="";this.S.params.KF===3&&(S="rotate(180deg)");
var k=e?`calc(96% - ${J}px)`:"96%";g.rI(this.element,{top:0,left:0,right:"",bottom:"",width:p?`${p}px`:"",height:Q?`${Q}px`:"","max-width":k,"max-height":k,margin:"",transform:""});this.uV(t);S={transform:S,top:"",left:"",width:p?`${p}px`:"",height:Q?`${Q}px`:"","max-width":"","max-height":""};k=this.X.zG;var w=this.X.Jn,f=this.X.hz;this.GH&&k!=null&&(w=50,k=Math.floor(k/3)*3+1);w=w*.96+2;switch(k){case 0:case 3:case 6:(e=this.X.T1.fontSizeIncrement)&&e>0&&this.X.KF!==2&&this.X.KF!==3&&(w=Math.max(w/
(1+e*2),2));S.left=`${w}%`;break;case 1:case 4:case 7:S.left=`${w}%`;let R=0;this.D||(R=this.U.offsetWidth);p||R?(p=p||R+1,S.width=`${p}px`,S["margin-left"]=e?`${p/-2-J/2}px`:`${p/-2}px`):(this.D&&(S.width="max-content"),S.transform+=" translateX(-50%)");break;case 2:case 5:case 8:S.right=`${100-w}%`}e=f*.96+2;switch(k){case 0:case 1:case 2:S.top=`${e}%`;break;case 3:case 4:case 5:S.top=`${e}%`;e=0;this.D||(e=this.element.clientHeight);(Q=Q||e)?(S.height=`${Q}px`,S["margin-top"]=`${Q/-2}px`):S.transform+=
" translateY(-50%)";break;case 6:case 7:case 8:S.bottom=`${100-e}%`}if(this.SX){switch(k){case 0:case 3:case 6:Q=Math.max(0,100-2*w);break;case 2:case 5:case 8:Q=Math.max(0,100-2*(100-w));break;default:Q=Math.max(0,2*Math.min(w-2,98-w))}S["max-width"]=J>0?`calc(${Q}% - ${J}px)`:`${Q}%`}g.rI(this.element,S);this.C&&(this.D?Q=this.y3:(t=rFg(this,t),Q=this.GH?t>0?this.U.offsetHeight/t:0:this.U.offsetHeight/t),this.C.style.height=`${Q}px`,this.C.style.width=`${Q}px`,this.element.style.paddingLeft=`${Q+
5}px`,this.element.style.paddingRight=`${Q+5}px`,this.D||(t=Number(this.element.style.marginLeft.replace("px",""))-Q-5,Q=Number(this.element.style.marginRight.replace("px",""))-Q-5,this.element.style.marginLeft=`${t}px`,this.element.style.marginRight=`${Q}px`))}uV(t){if(this.type===0&&this.S.params.BO!==void 0&&this.experiments.OL("web_enable_popon_asr_captions")){var p=t,Q=this.S.params.BO;if(p.length===0||Q<=0)t=[];else{t=[];for(let J=p.length-1;J>=0;J--){var e=p[J];t.unshift(e);let S=rFg(this,
t);if(S>Q){t.shift();typeof e.text==="string"&&(p=e.text.split("\n"),Q=S-Q,p.length-Q>0&&(Q=p.slice(Q),e=new EW(e.start,e.end-e.start,e.priority||0,e.windowId,Q.join("\n"),e.append,e.X),t.unshift(e)));break}}}}for(e=0;e<t.length&&t[e]===this.Z[e];e++);if(this.TH||this.Z.length>e)e=0,this.TH=!1,this.Z=[],this.L=this.sL=this.Kx=null,g.Sy(this.U);for(;e<t.length;e++)M9n(this,t[e])}MX(){return 0}YY(){return 0}toString(){return super.toString()}};var h1X=class{constructor(){this.U=this.time=this.mode=this.S=0;this.K=new l4m(this);this.L=new l4m(this);this.X=[];this.clear()}clear(){this.U=this.time=this.mode=0;this.X=[];this.reset()}reset(){this.mode=0;this.K.reset(0);this.L.reset(1)}},I2z=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],FYy=class{constructor(){this.type=0}set(t){this.type=t}get(){return this.type}},Arn=class{constructor(){this.state=this.Xv=this.Uu=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}Qc(){return this.state!==0}matches(t,p){return this.Qc()&&t===this.Uu&&p===this.Xv}},U3g=class{constructor(){this.timestamp=this.X=0}copy(t){this.X=t.X;
this.timestamp=t.timestamp}reset(){this.timestamp=this.X=0}},hH=class{constructor(t){this.L=t;this.U=[];this.X=this.S=this.row=0;this.style=new FYy;this.K=0;for(t=0;t<=15;t++){this.U[t]=[];for(let p=0;p<=32;p++)this.U[t][p]=new U3g}}updateTime(t){for(let p=1;p<=15;++p)for(let Q=1;Q<=32;++Q)this.U[p][Q].timestamp=t}debugString(){var t="\n";for(let p=1;p<=15;++p){for(let Q=1;Q<=32;++Q){let e=this.U[p][Q];t=e.X===0?t+"_":t+String.fromCharCode(e.X)}t+="\n"}return t}reset(t){for(let p=0;p<=15;p++)for(let Q=
0;Q<=32;Q++)this.U[p][Q].reset();this.K=t;this.X=0;this.S=this.row=1}},Y16=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],a2f=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],sVz=[193,201,211,218,220,252,8216,
161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,206,207,239,212,217,249,219,171,187],Bj6=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],crh=class{constructor(t){this.U=t;this.L=0;this.style=new FYy;this.C=new hH(this.U);this.Z=new hH(this.U);this.text=new hH(this.U);this.S=this.C;this.K=this.Z;this.X=this.S}reset(t,p){this.L=p;this.style.set(2);this.S=this.C;this.K=this.Z;this.X=this.S;var Q=(t<<
2)+(p<<1);this.C.reset(Q);this.Z.reset(Q);this.text.reset((t<<2)+(p<<1)+1)}},l4m=class{constructor(t){this.X=t;this.L=0;this.U=new crh(this.X);this.C=new crh(this.X);this.S=new Arn;this.K=this.U}reset(t){this.L=t;this.S.clear();this.K=this.U;this.U.reset(t,0);this.C.reset(t,1)}};var tue=class{K(){}};var Ft=class extends g.Xa{reset(){}};var jL=class extends g.wN{constructor(t,p,Q,e,J){super(t,t+p,{priority:Q,namespace:"captions"});this.id=e;this.params=J;this.X=[]}toString(){return super.toString()}},LP=0;var i5h=class extends Ft{constructor(t){super();this.K=t;this.pens={};this.V={};this.D={};this.L="_"+LP++;this.Z={};this.S=this.X=null;this.C=!0}reset(){this.Z={};this.S=this.X=null;this.C=!0}U(t,p){t=t.firstChild;t.getAttribute("format");p=p||0;Number.isFinite(p);t=Array.from(t.childNodes);for(var Q of t)if(Q.nodeType===1)switch(Q.tagName){case "head":var e=Q;break;case "body":var J=Q}if(e){e=Array.from(e.childNodes);for(var S of e)if(S.nodeType===1)switch(S.tagName){case "pen":Q=S.getAttribute("id");
e=this.pens;t={};var k=S.getAttribute("p");k&&Object.assign(t,this.pens[k]);k=bE(S,"b");k!=null&&(t.bold=k);k=bE(S,"i");k!=null&&(t.italic=k);k=bE(S,"u");k!=null&&(t.underline=k);k=gW(S,"et");k!=null&&(t.charEdgeStyle=k);k=gW(S,"of");k!=null&&(t.offset=k);k=dW(S,"bc");k!=null&&(t.background=k);k=dW(S,"ec");k!=null&&(t.QR=k);k=dW(S,"fc");k!=null&&(t.color=k);k=gW(S,"fs");k!=null&&k!==0&&(t.fontFamily=k);k=vG(S,"sz");k!==void 0&&(t.fontSizeIncrement=k/100-1);k=vG(S,"bo");k!==void 0&&(t.backgroundOpacity=
k/255);k=vG(S,"fo");k!==void 0&&(t.textOpacity=k/255);k=gW(S,"rb");k!=null&&k!==10&&k!==0&&(t.iQ=k>10?k-1:k);k=gW(S,"hg");k!=null&&(t.sF=k);e[Q]=t;break;case "ws":e=S.getAttribute("id");this.D[e]=AFz(this,S);break;case "wp":e=S.getAttribute("id"),this.V[e]=UzX(this,S)}}if(J){S=[];J=Array.from(J.childNodes);for(M of J)if(M.nodeType===1)switch(M.tagName){case "w":this.X=cFz(this,M,p,!1);(J=this.Z[this.X.id])&&J.end>this.X.start&&(J.end=this.X.start);this.Z[this.X.id]=this.X;S.push(this.X);break;case "p":var w=
M;t=p;J=[];e=w.getAttribute("w")||this.L;Q=!!bE(w,"a");t=(vG(w,"t")||0)+t;k=vG(w,"d")||5E3;Q||(!this.C&&this.S&&this.S.windowId===e&&this.S.end>t&&(this.S.end=t),this.S&&this.S.text==="\n"&&(this.S.text=""));let O=Q?6:5;var f=w.getAttribute("p");f=f?this.pens[f]:null;let Y=Array.from(w.childNodes);Y.length&&(this.C=w.getAttribute("d")!=null);for(w=0;w<Y.length;w++){var R=Y[w],z=void 0;w>0&&(Q=!0);let B;R.nodeType===1&&(B=R);if(B&&B.tagName==="s"){if((R=(R=B.getAttribute("p"))?this.pens[R]:null)&&
R.iQ&&(R.iQ===1?(R=Y.slice(w,w+4),R.length===4&&(z=h6X(t,k,e,Q,O,R,this.pens),w+=3)):z=h6X(t,k,e,Q,O,[B],this.pens)),!z){var y=B;z=t;R=k;var X=e,E=Q;let W=y.textContent?y.textContent:"";var b=y.getAttribute("p");b=b?this.pens[b]:null;y=vG(y,"t")||0;z=new EW(z+y,R-y,O,X,W,E,b)}}else z=new EW(t,k,O,e,R.textContent||"",Q,f);J.push(z);this.S=z}if(J.length>0){J[0].windowId===this.L&&(this.X=cFz(this,M,p,!0),S.push(this.X));for(let B of J)B.windowId=this.X.id,this.X.X.push(B),S.push(B)}}var M=S}else M=
[];return M}};var pFE=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),Qrh=class extends Ft{constructor(t){super();this.C=t;this.X=new Map;this.K=new Map;this.L=new Map;this.S=new Map}reset(){this.S.clear()}U(t,p){t=JSON.parse(t);if(!t)return[];if(t.pens){var Q=t.pens,e=0;for(var J of Q){Q={};var S=J.pParentId;S&&Object.assign(Q,this.X.get(S));J.bAttr&&(Q.bold=!0);J.iAttr&&(Q.italic=!0);J.uAttr&&(Q.underline=!0);S=J.ofOffset;S!=null&&(Q.offset=S);J.szPenSize!==void 0&&(Q.fontSizeIncrement=J.szPenSize/100-1);
S=J.etEdgeType;S!=null&&(Q.charEdgeStyle=S);J.ecEdgeColor!==void 0&&(Q.QR=GQ(J.ecEdgeColor));S=J.fsFontStyle;S!=null&&S!==0&&(Q.fontFamily=S);J.fcForeColor!==void 0&&(Q.color=GQ(J.fcForeColor));J.foForeAlpha!==void 0&&(Q.textOpacity=J.foForeAlpha/255);J.bcBackColor!==void 0&&(Q.background=GQ(J.bcBackColor));J.boBackAlpha!==void 0&&(Q.backgroundOpacity=J.boBackAlpha/255);(S=J.rbRuby)&&S!==10&&(Q.iQ=S>10?S-1:S,Q.textEmphasis=pFE.get(Q.iQ));J.hgHorizGroup&&(Q.sF=J.hgHorizGroup);this.X.set(e++,Q)}}if(t.wsWinStyles){e=
t.wsWinStyles;J=0;for(var k of e)e={},(Q=k.wsParentId)?Object.assign(e,this.L.get(Q)):Object.assign(e,this.C),k.mhModeHint!==void 0&&(e.XA=k.mhModeHint),k.juJustifCode!==void 0&&(e.textAlign=k.juJustifCode),k.pdPrintDir!==void 0&&(e.KF=k.pdPrintDir),k.sdScrollDir!==void 0&&(e.IZ=k.sdScrollDir),k.wfcWinFillColor!==void 0&&(e.windowColor=GQ(k.wfcWinFillColor)),k.wfoWinFillAlpha!==void 0&&(e.windowOpacity=k.wfoWinFillAlpha/255),this.L.set(J++,e)}if(t.wpWinPositions){J=t.wpWinPositions;k=0;for(var w of J)J=
{},(e=w.wpParentId)&&Object.assign(J,this.K.get(e)),w.ahHorPos!==void 0&&(J.Jn=w.ahHorPos),w.apPoint!==void 0&&(J.zG=w.apPoint),w.avVerPos!==void 0&&(J.hz=w.avVerPos),w.ccCols!==void 0&&(J.q3=w.ccCols),w.rcRows!==void 0&&(J.BO=w.rcRows),this.K.set(k++,J)}if(t.events){t=t.events;w=[];for(let F of t)if(k=(F.tStartMs||0)+p,J=F.dDurationMs||0,F.id)e=String(F.id),t=tj6(this,F,k,J,e),w.push(t),this.S.set(e,t);else{F.wWinId?e=F.wWinId.toString():(e="_"+LP++,t=tj6(this,F,k,J,e),w.push(t),this.S.set(e,t));
t=w;var f=F;J===0&&(J=5E3);Q=this.S.get(e);let Sh=(S=!!f.aAppend)?6:5,DS=f.segs,dc=null;f.pPenId&&(dc=this.X.get(f.pPenId));for(f=0;f<DS.length;f++){var R=DS[f],z=R.utf8;if(z){var y=R.tOffsetMs||0;let G7=null;R.pPenId&&(G7=this.X.get(R.pPenId));if((Q.params.XA!=null?Q.params.XA:Q.X.length>1?1:0)===2&&S&&z==="\n")continue;R=null;var X=[],E;if(E=G7&&G7.iQ===1)a:{E=DS;var b=f;if(b+3>=E.length||!E[b+1].pPenId||!E[b+2].pPenId||!E[b+3].pPenId){E=!1;break a}var M=E[b+1].pPenId;(M=this.X.get(M))&&M.iQ&&M.iQ===
2?(M=E[b+2].pPenId,M=this.X.get(M),!M||!M.iQ||M.iQ<3?E=!1:(M=E[b+3].pPenId,E=(M=this.X.get(M))&&M.iQ&&M.iQ===2?!0:!1)):E=!1}if(E)y=DS[f+1].utf8,R=DS[f+3].utf8,E=DS[f+2].utf8,b=this.X.get(DS[f+2].pPenId),z=l2m(z,y,E,R,b),R=new EW(k,J,Sh,e,z,S,G7),f+=3;else{if(z.indexOf("<")>-1){X=G7;E=dc;b=k;M=J;var O=y,Y=Sh,B=S;let PD=[];var W=g.az(`<html>${z}</html>`);if(!W.getElementsByTagName("parsererror").length&&W.firstChild?.childNodes.length)for(let AM of W.firstChild.childNodes){W=AM.textContent?.replace(/\n/g,
"")??"";if(AM.nodeType===3&&(!W||W.match(/^ *$/)!=null))continue;let kS={};Object.assign(kS,X||E);switch(AM?.tagName){case "b":kS.bold=!0;break;case "i":kS.italic=!0;break;case "u":kS.underline=!0}PD.push(new EW(b+O,M-O,Y,Q.id,W,B,kS))}X=PD}X.length||(X=[new EW(k+y,J-y,Sh,Q.id,z,S,G7||dc)])}if(X.length)for(let PD of X)t.push(PD),Q.X.push(PD);else R&&(t.push(R),Q.X.push(R))}S=!0}}p=w}else p=[];return p}};var enE=class extends g.q4{constructor(t,p,Q){super(t);this.videoData=p;this.audioTrack=Q;this.D=p.Dl}K(t,p,Q){yFz(this.videoData.videoId,t.vssId,Q.WC)}L(t){if(this.audioTrack)for(let p of this.audioTrack.captionTracks)g.FO(this.X,p);t.AE()}};var OZm=class extends lE{constructor(t,p,Q,e,J,S,k,w,f,R){super(t,p,Q,e,J,S,k,w,f,R);this.type=1}uV(t){var p=this.S.X;super.uV(t);for(t=t.length;t<p.length;t++){let J=p[t],S;if(e&&J.X===Q)S=e;else{S={};Object.assign(S,J.X);Object.assign(S,JJe);var Q=J.X;var e=S}M9n(this,J,S)}}},JJe={mH:!0};var iZX=class extends tue{constructor(t,p){super();this.trackData=t;this.C=p;this.version=this.L=this.U=this.byteOffset=0;this.S=[];this.X=new DataView(this.trackData)}K(t,p,Q,e,J){if(Q<e){let S="_"+LP++;Q=Q/1E3-this.C;e=e/1E3-this.C;t=new jL(Q,e-Q,5,S,{textAlign:0,zG:0,Jn:p*2.5,hz:t*5.33});J=new EW(Q,e-Q,5,S,J);this.S.push(t);this.S.push(J)}}},SYo=class extends Ft{constructor(t,p){super();this.S=t;this.K=p;this.track=this.K.languageName==="CC3"?4:0;this.X=new h1X;this.X.S=1<<this.track}U(t){t=new iZX(t,
this.S);if(pwy(t)){for(;t.byteOffset<t.X.byteLength;)for(t.version===0?t.U=TQ(t)*(1E3/45):t.version===1&&(t.U=TQ(t)*4294967296+TQ(t)),t.L=rW(t);t.L>0;t.L--){var p=rW(t);let Q=rW(t),e=rW(t);p&4&&(p&3)===this.track&&(this.track===0||this.track===1)&&(p=this.X,p.X.push({time:t.U,type:this.track,o_:Q,eA:e,order:p.X.length}))}OzE(this.X,t);return t.S}return[]}reset(){this.X.clear()}};var Yjz=class extends lE{constructor(t,p,Q,e,J,S,k,w,f,R){super(t,p,Q,e,J,S,k,w,f,R);this.type=2;this.EL=[];this.Sv=this.Ph=this.aL=0;this.gm=NaN;this.B0=0;this.KH=null;this.It=new g.gq(this.H0,433,this);this.C&&(R.createClientVe(this.C,this,167342),this.O(this.C,"click",()=>{R.logClick(this.C)}),t=new g.Z_(this.element,!0),g.C(this,t),t.subscribe("hoverstart",()=>{R.logVisibility(this.C,!0)},this));
g.M3(this.element,"ytp-caption-window-rollup");g.C(this,this.It);g.rI(this.element,"overflow","hidden")}PT(){g.dq(this.It)}H0(){this.element.removeEventListener("transitionend",this.H0,!1);g.x9(this.element,"ytp-rollup-mode");this.V(this.KH,!0)}YY(){return this.K?this.Sv:this.Ph}MX(){return this.K?this.Ph:this.Sv}V(t,p){this.KH=t;if(this.S.params.BO){var Q=0;for(let e=0;e<this.Z.length&&Q<t.length;e++)this.Z[e]===t[Q]&&Q++;Q>0&&Q<t.length&&(t=this.Z.concat(t.slice(Q)));this.B0=this.Sv;this.Ph=this.Sv=
0;super.V(t);Sj6(this,p)}super.V(t)}};var ksO=class{constructor(t,p,Q,e){this.J=t;this.L=p;this.logger=Q;this.T6=e;this.VA=[];this.X=null;this.U=[];this.L$=[];this.S=null;this.z6={X5U:()=>this.S,
gG:()=>this.VA,
pHm:J=>{this.U=J},
SHQ:()=>this.U};
t=this.J.j().experiments.X("html5_override_micro_discontinuities_threshold_ms");this.K=t>0?t:10}unload(){this.S!=null&&(this.J.removeEventListener("sabrCaptionsDataLoaded",this.S),this.S=null);this.VA=[];this.X=null;this.U=[];this.J.publish("sabrCaptionsBufferedRangesUpdated",this.VA)}WI(t){return{formatId:g.HR(t.info.mX.info,this.T6),Cx:t.info.Cx+(this.T6?0:1),startTimeMs:t.info.K*1E3,durationMs:t.info.Z*1E3}}};var wFz=class extends g.q4{constructor(t,p){super(p);this.S=t;this.J=p;this.logger=new g.vR("caps");this.V=this.Sv=null;this.bV=new ksO(this.J,this,this.logger,this.S.T6)}K(t,p,Q){this.U();p=t.getId();p=p!=null&&p in this.S.X?this.S.X[p]:null;p||(p=t.languageCode,p=this.S.isManifestless?u8n(this,p,"386"):u8n(this,p));p&&(this.V=t,this.Sv=p,R1z(this.bV,Q),this.J.publish("sabrCaptionsTrackChanged",g.HR(p.info,this.S.T6)))}L(t){var p=this.S.isManifestless?o9m(this,"386"):o9m(this);for(let Q of p)g.FO(this.X,
Q);t.AE()}U(){this.V&&(this.V=this.Sv=null,this.bV.unload(),this.J.publish("sabrCaptionsTrackChanged",null))}C(){return""}};var z1g="WEBVTT".split("").map(t=>t.charCodeAt(0)),E9n=class extends Ft{constructor(){super()}U(t,p){t instanceof ArrayBuffer&&(t=g.Tp(new Uint8Array(t)));
var Q=[];t=t.split(f9E);for(let b=1;b<t.length;b++){var e=t[b],J=p;if(e!==""&&!nqZ.test(e)){var S=AH.exec(e);if(S&&S.length>=4){var k=ZC(S[1]),w=ZC(S[2])-k;k+=J;var f=(S=S[3])?S.split(" "):[];S={};var R=null;var z="";var y=null,X="";for(let M of f){f=M.split(":");if(f.length!==2)continue;var E=f[1];switch(f[0]){case "line":f=E.split(",");f[0].endsWith("%")&&(R=f[0],S.hz=Number.parseInt(R,10),f.length===2&&(z=f[1].trim()));break;case "position":f=E.split(",");y=f[0];S.Jn=Number.parseInt(y,10);f.length===
2&&(X=f[1].trim());break;case "align":switch(E){case "start":S.textAlign=0;break;case "middle":S.textAlign=2;break;case "end":S.textAlign=1}}}R||z||(z="end");if(!y)switch(S.textAlign){case 0:S.Jn=0;break;case 1:S.Jn=100;break;case 2:S.Jn=50}if(S.textAlign!=null){R=0;switch(z){case "center":R+=3;break;case "end":R+=6;break;default:R+=0}switch(X){case "line-left":R+=0;break;case "center":R+=1;break;case "line-right":R+=2;break;default:switch(S.textAlign){case 0:R+=0;break;case 2:R+=1;break;case 1:R+=
2}}z=R<0||R>8?7:R;S.zG=z}e=e.substring(AH.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");X=S;S={};if(e.indexOf("<")<0&&e.indexOf("&")<0)J=m3o(k,w,5,X),k=new EW(k,w,5,J.id,e,!1,g.Yf(S)?void 0:S),Q.push(J),Q.push(k),J.X.push(k);else for(z=e.split(RnE),z.length===1?(e=5,X=m3o(k,w,e,X)):(R=e=6,X=Object.assign({q3:32},X),X=new jL(k,w,R,"_"+LP++,X)),Q.push(X),R=k,y=0;y<z.length;y++)if(f=z[y],y%2===0){E=g.az(`<html>${f}</html>`);let M;E.getElementsByTagName("parsererror").length?(M=E.createElement("span"),
M.appendChild(E.createTextNode(f))):M=E.firstChild;$3X(this,R,w-(R-k),e,X,y>0,M,S,Q)}else R=ZC(f)+J}AH.lastIndex=0}}return Q}},nqZ=/^NOTE/,f9E=/(?:\r\n|\r|\n){2,}/,AH=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),RnE=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var N2h=class extends g.Xa{constructor(t,p){super();this.J=t;this.Hh=p;this.X=null;this.Os=this.J.Rp();this.logger=new g.vR("caps")}clear(){this.X&&this.X.dispose();this.X=null}reset(){this.X&&this.X.reset()}qQ(){super.qQ();this.clear()}};var g9E={windowColor:"#080808",windowOpacity:0,textAlign:2,zG:7,Jn:50,hz:100,isDefault:!0,T1:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},bZo={windowColor:"#080808",windowOpacity:0,textAlign:0,zG:7,Jn:50,hz:100,isDefault:!0,T1:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.hQ("captions",class extends g.Cv{constructor(t){super(t);this.J=t;this.gm=[];this.IL={};this.Zr={};this.Z=!1;this.U="NONE";this.X=this.D=this.bV=this.aL=this.V3=null;this.H0={AE:()=>{this.AE()},
WC:(e,J,S,k,w=0)=>{var f=Number(this.videoData.j().MQ().X.iV(g.U1D)??0);w>0&&f>0&&this.videoData.lengthSeconds>0&&w/this.videoData.lengthSeconds>f?this.J.XU("tts",{dropcap:w}):this.WC(e,J,S,k)}};
this.S=null;this.Hh=this.J.j();this.videoData=this.J.getVideoData();this.GH=this.J.bW();this.L={T1:{}};this.C={T1:{}};g.G$(this.videoData)?this.U="OFFLINE":g.QhH(this.videoData,this.J)?this.U="HLS":Nqy(this.videoData,this.J)?this.U="SABR_LIVE":g.esh(this.videoData,this.J)?this.U="LIVE":this.videoData.captionTracks.length?this.U="INNERTUBE":this.videoData.uV&&(this.U="TTS");this.Kx=this.Hh.controlsType==="3";this.uV=new N2h(this.J,this.Hh);this.EL=new g.u_(this);this.V=new g.CR({W:"div",B:"ytp-caption-window-container",
N:{id:"ytp-caption-window-container"}});this.Sv={top:0,right:0,bottom:0,left:0,width:1,height:1};var p=null,Q=g.or("yt-html5-player-modules::subtitlesModuleData");Q&&(p=new g.Qg(Q));this.storage=p;p=t.ot();this.Es=!!p?.sL();this.Dr=!!p?.aL();this.K=MT(this);this.Ph=v9f(this);g.C(this,this.uV);this.K?this.sL=this.TH=null:(this.TH=new g.b2(this.RH,void 0,this),g.C(this,this.TH),this.sL=new g.gq(this.B0,2E3,this),g.C(this,this.sL));g.C(this,this.EL);g.Ah(this.player,this.V.element,4);g.C(this,this.V);
this.K||this.EL.O(t,"resize",this.SX);p=g.js(this.Hh)&&!g.On()&&!this.J.isFullscreen();Q=this.Hh.MQ().X.iV(g.D5h)&&g.es(this.Hh)&&g.UA;(this.Fd=(p||Q)&&!this.K&&!this.Ph)&&this.EL.O(t,p?"resize":"fullscreentoggled",this.YY);this.EL.O(t,"onPlaybackAudioChange",this.aH);this.EL.O(t,g.yP("captions"),e=>{this.onCueRangeEnter(e)});
this.EL.O(t,g.mn("captions"),e=>{this.onCueRangeExit(e)});
Ic(this,uE()||{});g.I3(this.player,"onCaptionsModuleAvailable");this.U==="HLS"&&this.K&&(t=this.J.ot().Us(),this.Dr&&this.EL.O(t.textTracks,"addtrack",this.MX))}qQ(){if(this.K||this.Ph){let t=this.J.ot();t&&!t.UL()&&t.V()}else xG(this,!1);super.qQ()}Y5(){return this.Hh.Y("html5_honor_caption_availabilities_in_audio_track")&&this.U!=="LIVE"&&this.U!=="SABR_LIVE"}LZ(){if(this.Kx)return this.K||this.Ph;if(this.U==="HLS")return this.K;var t=this.getAudioTrack();if(this.Y5()){if(!t.captionTracks.length)return!1;
if(!this.X)return!0}t=Rc(t,g.C$(this.Hh));return t==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:t==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?YG(this):OW(this)||YG(this)?!0:rrz(this)}load(){super.load();this.D=this.getAudioTrack();if(this.X)this.S&&(this.uV.clear(),this.K?Tqz(this,!0):this.player.getPresentingPlayerType()!==3&&this.X.K(this.S,"json3",this.H0),this.U!=="HLS"&&this.K||this.Ph||ac(this)||g.I3(this.player,"captionschanged",g.R2(this.S)));else{let t;this.U==="OFFLINE"?t=new enE(this.player,this.videoData,
this.getAudioTrack()):this.U==="SABR_LIVE"?t=new wFz(this.videoData.X,this.player):this.U==="HLS"?t=new BqT(this.player):this.U==="LIVE"?t=new HZh(this.videoData.X,this.player):this.U==="INNERTUBE"?t=new g.OB(this.player,this.videoData,this.getAudioTrack()):t=new g.YY(this.player,this.videoData.uV,this.videoData.videoId,g.sdM(this.videoData),this.videoData.QE,this.videoData.eventId);this.X=t;g.C(this,this.X);this.X.L(this.H0)}}unload(){this.K&&this.S?Tqz(this,!1):(this.sL&&this.sL.rp(),this.player.RI("captions"),
this.gm=[],this.X&&this.X.U(),this.uV.clear(),this.bV&&this.player.kq(this.bV),this.SX());super.unload();this.player.XV();g.I3(this.player,"captionschanged",{})}create(){this.LZ()&&this.load();var t;a:{if(this.Hh.Y("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(t=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let p of t)if(p.kind==="asr"&&p.languageCode===
"en"){t=!0;break a}t=!1}t&&this.J.publish("showpromotooltip",this.V.element)}AE(){var t=Rc(this.player.getAudioTrack(),g.C$(this.Hh));t=t==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?BG(this,this.Z):t==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&YG(this)?sW(this):OW(this)||this.Z||rrz(this)?BG(this,this.Z):YG(this)?sW(this):null;this.U!=="HLS"&&this.K||this.Ph?Mjz(this,t):(!this.S&&t&&KP(this,t),g.I3(this.player,"onCaptionsTrackListChanged"),g.xD(this.player,"onApiChange"))}AT(){var t=this.J.ot().Us().textTracks,
p=null;for(let Q=0;Q<t.length;Q++)if(t[Q].mode==="showing")a:{p=g.dy(this.X.X,!0);for(let e=0;e<p.length;e++)if(p[e].toString()===t[Q].id){p=p[e];break a}p=null}(this.loaded?this.S:null)!==p&&KP(this,p,!0)}MX(){this.X?.L(this.H0)}GO(){!this.S&&this.K||this.unload()}WC(t,p,Q,e){if(t){HG(this,this.S??void 0);this.X.Ph()&&(this.gm=[],this.J.RI("captions"),nP(this.TH),this.uV.reset());a:{var J=this.uV;e=e||0;Q=D3e(J,t,Q||0);t=[];try{for(let Y of Q){let B=Y.trackData,W=Y.hi,F=J.Hh.Y("safari_live_drm_captions_fix");
if(typeof B!=="string"){Q=t;var S=Q.concat;if(F&&yrh(B))var k=LYf(J,B,W);else{var w=J,f=p,R=B,z=W,y=e;if(!QLE(R))throw Error("Invalid binary caption track data");w.X||(w.X=new SYo(y,f));k=w.X.U(R,z)}var X=S.call(Q,k)}else{if(B.substring(0,6)==="WEBVTT")var E=t.concat(LYf(J,B,W));else{Q=t;var b=Q.concat;b:{f=J;w=p;if(B[0]==="{")try{f.X||(f.X=new Qrh(jLm(w)));var M=f.X.U(B,W);break b}catch(dc){g.DK(dc);M=[];break b}let Sh=g.az(B);if(!Sh||!Sh.firstChild){let dc=Error("Invalid caption track data");dc.params=
B;throw dc;}if(Sh.firstChild.tagName==="timedtext"){if(Number(Sh.firstChild.getAttribute("format"))===3){R=Sh;f.X||(f.X=new i5h(jLm(w)));M=f.X.U(R,W);break b}let dc=Error("Unsupported subtitles format in web player (Format2)");dc.params=B;throw dc;}if(Sh.firstChild.tagName==="transcript"){let dc=Error("Unsupported subtitles format in web player (Format1)");dc.params=B;throw dc;}let DS=Error("Invalid caption track data");DS.params=B;throw DS;}E=b.call(Q,M)}X=E}t=X}var O=t;break a}catch(Y){g.be(J.logger,
187101178,`Captions parsing failed: ${Y.message}. `);J.clear();O=[];break a}O=void 0}this.Hh.Y("html5_sabr_live_support_subfragmented_captions")&&this.X instanceof wFz&&(p=this.X.bV,J=[],O.length>0&&(J=O.slice(p.U.length)),p.U=!p.X||p.X.info.Wp?[]:O,O=J);O.length>0&&(p=this.S,this.Gh(p,!!p,ac(this)?"g":this.Z?"m":"s"));this.player.kq(O,void 0,this.U==="LIVE"||this.U==="SABR_LIVE");!this.Z||this.Ph||ac(this)||g.iS(this.Hh)||g.L$(this.Hh)||g.B_(this.Hh)||this.Hh.EL==="shortspage"||this.player.isInline()||
(this.sL.rp(),O=Fkm({zG:0,Jn:5,hz:5,BO:2,textAlign:0,KF:0,lang:"en-GB"}),this.aL=[O],p=["Click "," for settings"],this.V3||(J=new g.dK(g.Ee()),g.C(this,J),this.V3=J.element),J=O.end-O.start,(X=g.nc(this.S))&&this.aL.push(new EW(O.start,J,0,O.id,X)),this.aL.push(new EW(O.start,J,0,O.id,p[0]),new EW(O.start,J,0,O.id,this.V3,!0),new EW(O.start,J,0,O.id,p[1],!0)),this.player.kq(this.aL),g.Vj(this.sL));!this.Z||this.Ph||ac(this)||(this.Hh.Y("enable_player_captions_persistence_state_machine")?qT(this,!0):
g.C$(this.Hh)?WG(this,!0):PG(this,!0),this.D&&(this.D.K=this.S),this.player.XV());this.Z=!1}}onCueRangeEnter(t){this.gm.push(t);nP(this.TH)}onCueRangeExit(t){g.Qm(this.gm,t);this.X instanceof HZh&&this.X.Sv&&this.player.gT([t]);nP(this.TH)}getCaptionWindowContainerId(){return this.V.element.id}B0(){Vjg(this,this.aL);this.aL=null}RH(){if(!this.Fd||!this.K){this.TH.stop();g.ay(this.Zr);this.gm.sort(g.zq);var t=this.gm;if(this.bV){let p=g.BD(t,function(Q){return this.bV.indexOf(Q)===-1},this);
p.length&&(t=p)}for(let p of t)p instanceof jL?x3n(this,p):C2e(this,p);for(let [p,Q]of Object.entries(this.IL)){let e=p,J=Q;this.Zr[e]?(J.element.parentNode||(J instanceof Yjz||J instanceof OZm||g.dT(this.IL,(S,k)=>{k!==e&&S.S.params.zG===J.S.params.zG&&S.S.params.Jn===J.S.params.Jn&&S.S.params.hz===J.S.params.hz&&(S.dispose(),delete this.IL[k]);return k===e},this),this.V.element.appendChild(J.element)),J.V(this.Zr[e])):(J.dispose(),delete this.IL[e])}}}tA(){Ic(this,{},!0);
g.I3(this.player,"captionssettingschanged")}zI(){var t=this.Hh.Y("enable_player_captions_new_style_defaults")?bZo:g9E,p=t.T1;t={background:p.background,backgroundOpacity:p.backgroundOpacity,charEdgeStyle:p.charEdgeStyle,color:p.color,fontFamily:p.fontFamily,fontSizeIncrement:p.fontSizeIncrement,fontStyle:p.bold&&p.italic?3:p.bold?1:p.italic?2:0,textOpacity:p.textOpacity,windowColor:t.windowColor,windowOpacity:t.windowOpacity};p=uE()||{};p.background!=null&&(t.background=p.background);p.backgroundOverride!=
null&&(t.backgroundOverride=p.backgroundOverride);p.backgroundOpacity!=null&&(t.backgroundOpacity=p.backgroundOpacity);p.backgroundOpacityOverride!=null&&(t.backgroundOpacityOverride=p.backgroundOpacityOverride);p.charEdgeStyle!=null&&(t.charEdgeStyle=p.charEdgeStyle);p.charEdgeStyleOverride!=null&&(t.charEdgeStyleOverride=p.charEdgeStyleOverride);p.color!=null&&(t.color=p.color);p.colorOverride!=null&&(t.colorOverride=p.colorOverride);p.fontFamily!=null&&(t.fontFamily=p.fontFamily);p.fontFamilyOverride!=
null&&(t.fontFamilyOverride=p.fontFamilyOverride);p.fontSizeIncrement!=null&&(t.fontSizeIncrement=p.fontSizeIncrement);p.fontSizeIncrementOverride!=null&&(t.fontSizeIncrementOverride=p.fontSizeIncrementOverride);p.fontStyle!=null&&(t.fontStyle=p.fontStyle);p.fontStyleOverride!=null&&(t.fontStyleOverride=p.fontStyleOverride);p.textOpacity!=null&&(t.textOpacity=p.textOpacity);p.textOpacityOverride!=null&&(t.textOpacityOverride=p.textOpacityOverride);p.windowColor!=null&&(t.windowColor=p.windowColor);
p.windowColorOverride!=null&&(t.windowColorOverride=p.windowColorOverride);p.windowOpacity!=null&&(t.windowOpacity=p.windowOpacity);p.windowOpacityOverride!=null&&(t.windowOpacityOverride=p.windowOpacityOverride);return t}NA(t,p){var Q={};Object.assign(Q,uE());Object.assign(Q,t);Ic(this,Q,p);g.I3(this.player,"captionssettingschanged")}SX(){!this.K&&this.loaded&&(g.bX(this.IL,function(t,p){t.dispose();delete this.IL[p]},this),this.RH())}l0(t,p){switch(t){case "fontSize":if(isNaN(p))break;
t=g.jP(p,-2,4);this.NA({fontSizeIncrement:t});return t;case "reload":p&&!this.K&&KP(this,this.S,!0);break;case "stickyLoading":p!==void 0&&this.Hh.bV&&(this.Hh.Y("enable_player_captions_persistence_state_machine")?qT(this,!(!p||!p.userInitiated)):g.C$(this.Hh)?WG(this,!!p):PG(this,!!p));break;case "track":return a4m(this,p);case "tracklist":return this.X?g.WD(g.dy(this.X.X,!(!p||!p.includeAsr)),Q=>g.R2(Q)):[];
case "translationLanguages":return this.X?this.X.D.map(Q=>Object.assign({},Q)):[];
case "sampleSubtitles":this.K||p===void 0||xG(this,!!p);break;case "sampleSubtitlesCustomized":this.K||xG(this,!!p,p);break;case "recommendedTranslationLanguages":return g.pc();case "defaultTranslationSourceTrackIndices":return this.X?this.X.IL:[]}}getOptions(){var t="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Hh.bV&&t.push("stickyLoading");return t}OO(){var t=this.S;if(this.J.kB("captions")){if(this.Hh.Y("html5_modify_caption_vss_logging"))return(t=this.videoData.TP??
null)?{cc:g.VMb(t)}:{};if(t){let p=t.vssId;t.translationLanguage&&p&&(p=`t${p}.${g.Nw(t)}`);return{cc:p}}}return{}}e5(t){this.isSubtitlesOn()?(this.Hh.Y("enable_player_captions_persistence_state_machine")&&t?qT(this,!1):g.C$(this.Hh)?WG(this,!1):PG(this,!1),HG(this),KP(this,null,!0)):this.J0(t)}J0(t){var p=ac(this)||!this.S?BG(this,!0):this.S;p&&this.fd(p.vssId,"m");this.isSubtitlesOn()||KP(this,p,this.Hh.Y("enable_player_captions_persistence_state_machine")?t:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.S&&!ac(this)}aH(){var t=ac(this);YG(this,t)?KP(this,this.getAudioTrack().X,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Y5()&&(this.Z=!1,this.S=null,this.X&&(this.X.dispose(),this.X=null)),this.LZ()&&(t?KP(this,BG(this,!1),!1):this.load()))}aV(t){t&&(this.Sv={top:t.top,right:t.right,bottom:t.bottom,left:t.left,width:1-t.left-t.right,height:1-t.top-t.bottom},this.V.element.style.top=`${this.Sv.top*100}%`,this.V.element.style.left=`${this.Sv.left*100}%`,this.V.element.style.width=
`${this.Sv.width*100}%`,this.V.element.style.height=`${this.Sv.height*100}%`,this.V.element.style.position="absolute",t=qjh(this))&&(this.V.element.style.width=`${t.width}px`,this.V.element.style.height=`${t.height}px`)}onVideoDataChange(t,p){t==="newdata"&&(this.videoData=p,this.loaded&&this.unload(),this.Z=!1,this.S=null,this.X&&(this.X.dispose(),this.X=null,g.I3(this.player,"captionschanged",{})),this.LZ()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}YY(){if(this.Hh.MQ().X.iV(g.D5h)){this.loaded&&
this.unload();var t=this.J.ot();t&&!t.UL()&&t.V();this.Kx=this.J.isFullscreen()||this.Hh.controlsType==="3";this.K=MT(this);this.Ph=v9f(this);this.X&&(this.K||this.Ph)&&Mjz(this,null)}else(t=this.J.ot())&&!t.UL()&&t.V(),this.J.isFullscreen()?(this.K=this.Kx=!0,this.loaded&&this.AE()):(this.Kx=this.Hh.controlsType==="3",this.K=MT(this));KP(this,this.S)}y3(){var t=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;t&&g.Gk(this.player,"innertubeCommand",
t)}Gh(t,p,Q){var e=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,J="";t&&(J=t.vssId,J=J.replace(e,""));var S="";t&&t.getId()&&(S=t.getId()||"");t&&t.getXtags()&&(t=t.getXtags(),t=t.replace(e,""),S=S.concat(`;${t}`));this.U==="HLS"&&(S="");this.J.Gh(p?J:"",p?S:"",Q)}fd(t,p){t=(t||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");t.length>0&&this.J.fd(t,p)}});})(_yt_player);
