(function(g){var window=this;'use strict';var xtZ=function(t,p){g.Gk(t,"onAutonavCoundownStarted",p)},COm=function(t){return t.isBackground()&&t.cN()},qYh=function(t,p){p=p.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
t.Ph=p?.navigationEndpoint;p=p?.trackingParams;t.playButton&&p&&t.J.setTrackingParams(t.playButton.element,p)},w8=function(t){var p=SG(t),Q=Math,e=Q.min;
var J=t.Z?Date.now()-t.Z:0;Q=e.call(Q,J,p);k_(t,Math.ceil((p-Q)/1E3));p-Q<=500&&t.X()?t.select(!0):t.X()&&t.V.start()},k_=function(t,p=-1){t=t.S.wm("ytp-autonav-endscreen-upnext-header");
g.Sy(t);if(p>=0){p=String(p);let e="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],J="Up next in $SECONDS".indexOf(e);if(J>=0){var Q=g.ey("Up next in $SECONDS".slice(0,J));t.appendChild(Q);Q=g.Qp("span");g.TL(Q,"ytp-autonav-endscreen-upnext-header-countdown-number");g.nj(Q,p);t.appendChild(Q);p=g.ey("Up next in $SECONDS".slice(J+e.length));t.appendChild(p);return}}g.nj(t,"Up next")},SG=function(t){return t.J.isFullscreen()?(t=t.J.getVideoData().pR,t===-1||t===void 0?8E3:t):t.J.vv()>=0?t.J.vv():
t.J.j().experiments.X("autoplay_time")||1E4},fT=function(t,p){p=O5g(t,p);
var Q=Math,e=Q.min;var J=(0,g.l)()-t.Z;Q=e.call(Q,J,p);p=p===0?1:Math.min(Q/p,1);t.gm.setAttribute("stroke-dashoffset",`${-211*(p+1)}`);p>=1&&t.X()&&!t.isCasting()?t.select(!0):t.X()&&t.S.start()},O5g=function(t,p){return p?p:t.api.isFullscreen()?(t=t.api.getVideoData().pR,t===-1||t===void 0?8E3:t):t.api.vv()>=0?t.api.vv():t.api.j().experiments.X("autoplay_time")||1E4},nT=function(t){return g.Ud(t.player)&&t.Z()&&!t.U},R9=function(t){var p=t.rW();
p!==t.V&&(t.V=p,t.player.publish("autonavvisibility"))},N8=function(t){return g.Ud(t.player)&&t.Z()&&!t.K},uF=function(t){var p=t.rW();
p!==t.Ph&&(t.Ph=p,t.player.publish("autonavvisibility"))},YYT=function(t){t=t.j();
return t.bX&&!t.disableOrganicUi},a9T=function(t){var p=t.player.getVideoData();
if(!p||t.X===p.Fd)return!1;t.X=p.Fd;return!0},srf=function(t){t.player.RI("endscreen");
var p=t.player.getVideoData();p=new g.wN(Math.max((p.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var Q=new g.wN(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});t.player.kq([p,Q])};
g.N4.prototype.vv=g.eh(15,function(){return this.app.vv()});
g.io.prototype.vv=g.eh(14,function(){return this.getVideoData().aT});
g.Rj.prototype.xI=g.eh(13,function(t){this.ZN().xI(t)});
g.K6.prototype.xI=g.eh(12,function(t){this.J$!==t&&(this.J$=t,this.YV())});
var o9=class extends g.CR{constructor(t){super({W:"div",B:"ytp-autonav-endscreen-countdown-overlay"});this.cancelCommand=this.Ph=void 0;this.Z=0;t.Y("web_post_play_autonav_embiggening")&&g.M3(this.element,"ytp-autonav-endscreen-upnext-updated");this.container=new g.CR({W:"div",B:"ytp-autonav-endscreen-countdown-container"});g.C(this,this.container);this.container.Wh(this.element);var p=t.j(),Q=p.K;this.J=t;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.O(t,"videodatachange",
this.onVideoDataChange);this.S=new g.CR({W:"div",B:"ytp-autonav-endscreen-upnext-container",N:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},A:[{W:"div",B:"ytp-autonav-endscreen-topbar-container",A:[{W:"div",B:"ytp-autonav-endscreen-upnext-header"},{W:"div",B:"ytp-autonav-endscreen-upnext-alternative-header",nx:"{{autoplayAlternativeHeader}}"}]},{W:"a",B:"ytp-autonav-endscreen-link-container",
N:{href:"{{url}}",target:Q?p.Sv:""},A:[{W:"div",B:"ytp-autonav-endscreen-upnext-thumbnail",N:{style:"{{background}}"},A:[{W:"div",N:{"aria-label":"{{timestamp}}"},Jr:["ytp-autonav-timestamp"],nx:"{{duration}}"},{W:"div",Jr:["ytp-autonav-live-stamp"],nx:"Live"},{W:"div",Jr:["ytp-autonav-upcoming-stamp"],nx:"Upcoming"}]},{W:"div",B:"ytp-autonav-endscreen-video-info",A:[{W:"div",B:"ytp-autonav-endscreen-premium-badge"},{W:"div",B:"ytp-autonav-endscreen-upnext-title",nx:"{{title}}"},{W:"div",B:"ytp-autonav-endscreen-upnext-author",
nx:"{{author}}"},{W:"div",B:"ytp-autonav-view-and-date",nx:"{{views_and_publish_time}}"},{W:"div",B:"ytp-autonav-author-and-view",nx:"{{author_and_views}}"}]}]}]});g.C(this,this.S);this.S.Wh(this.container.element);Q||this.O(this.S.wm("ytp-autonav-endscreen-link-container"),"click",this.EL);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.S.wm("ytp-autonav-endscreen-link-container"),this,115128);this.closeButton=new g.CR({W:"button",B:"ytp-autonav-endscreen-upnext-header-close-button",
N:{"aria-label":"Cancel auto-play"}});g.C(this,this.closeButton);t.Y("web_post_play_autonav_embiggening")&&(this.closeButton.listen("click",this.IL,this),this.J.createClientVe(this.closeButton.element,this,115129),this.S.wm("ytp-autonav-endscreen-topbar-container").appendChild(this.closeButton.element));this.overlay=new g.CR({W:"div",B:"ytp-autonav-overlay"});g.C(this,this.overlay);this.overlay.Wh(this.container.element);this.C=new g.CR({W:"div",B:"ytp-autonav-endscreen-button-container"});g.C(this,
this.C);this.C.Wh(this.container.element);this.cancelButton=new g.CR({W:"button",Jr:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],N:{"aria-label":"Cancel auto-play"},nx:"Cancel"});g.C(this,this.cancelButton);this.cancelButton.Wh(this.C.element);this.cancelButton.listen("click",this.IL,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.CR({W:"a",Jr:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button","ytp-autonav-endscreen-upnext-button-rounded"],N:{href:"{{url}}",role:"button","aria-label":"Play next video"},nx:"Play now"});g.C(this,this.playButton);this.playButton.Wh(this.C.element);this.playButton.listen("click",this.EL,this);this.J.createServerVe(this.playButton.element,this.playButton,!0);(p=this.J.getVideoData())&&qYh(this,p);this.V=new g.gq(()=>{w8(this)},500);
g.C(this,this.V);this.Sv();this.O(t,"autonavvisibility",this.Sv)}D(t){this.suggestion!==t&&(this.suggestion=t,g.IQ(this.S,t),this.playButton.updateValue("url",this.suggestion.KX()),this.redraw())}redraw(){var t=this.J.IJ(!0,this.J.isFullscreen());g.q3(this.container.element,"ytp-autonav-endscreen-small-mode",this.EH(t));g.q3(this.container.element,"ytp-autonav-endscreen-is-premium",!!this.suggestion&&!!this.suggestion.Ed);g.q3(this.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!this.J.rW());
g.q3(this.J.getRootNode(),"countdown-running",this.X());g.q3(this.container.element,"ytp-player-content",this.J.rW());this.J.Y("web_post_play_autonav_embiggening")||g.rI(this.overlay.element,{width:`${t.width}px`});if(this.J.Y("web_post_play_autonav_embiggening")){var p=this.J.getRootNode().getBoundingClientRect();t=Math.min(720,p.width*.5);var Q=t*.5625;p=p.height-36-60;Q>p&&(Q=p,t=16/9*Q);g.rI(this.S.wm("ytp-autonav-endscreen-upnext-thumbnail"),{height:`${Q}px`,width:`${t}px`});g.rI(this.container.element,
{width:`${t}px`})}this.X()||(this.J.rW()?k_(this,Math.round(SG(this)/1E3)):k_(this),t=!!this.suggestion&&!!this.suggestion.Sw,Q=this.J.getVideoData(),Q=Q.autonavState===1&&Q.It&&this.J.rW()?!1:this.J.rW()||!(this.suggestion&&this.suggestion.Sw),g.q3(this.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!Q&&t),g.q3(this.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",Q&&!t),this.C.Di(this.J.rW()))}X(){return this.Z>0}L(){this.X()||(this.Z=Date.now(),w8(this),
xtZ(this.J,SG(this)),g.q3(this.J.getRootNode(),"countdown-running",this.X()))}K(){this.U();w8(this);var t=this.S.wm("ytp-autonav-endscreen-upnext-header");t&&g.nj(t,"Up next")}U(){this.X()&&(this.V.stop(),this.Z=0)}select(t=!1){this.J.nextVideo(!1,t);this.U()}EL(t){g.u9(t,this.J)&&(t.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):t.currentTarget===this.S.wm("ytp-autonav-endscreen-link-container")&&(t=this.S.wm("ytp-autonav-endscreen-link-container"),this.J.logVisibility(t,
!0),this.J.logClick(t)),this.Ph?(g.Gk(this.J,"innertubeCommand",this.Ph),this.U()):this.select())}IL(){this.J.logClick(this.cancelButton.element);g.PV(this.J,!0);this.cancelCommand&&g.Gk(this.J,"innertubeCommand",this.cancelCommand)}onVideoDataChange(t,p){qYh(this,p);this.cancelCommand=p.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}Sv(){var t=this.J.rW();this.W0!==t&&this.Di(t);this.redraw();this.J.logVisibility(this.container.element,
t);this.J.logVisibility(this.cancelButton.element,t);this.J.logVisibility(this.S.wm("ytp-autonav-endscreen-link-container"),t);this.J.logVisibility(this.playButton.element,t)}EH(t){return t.width<400||t.height<459}};var zR=class extends g.CR{constructor(t,p){super({W:"div",Jr:["html5-endscreen","ytp-player-content",p||"base-endscreen"]});this.created=!1;this.player=t}create(){this.created=!0}destroy(){this.created=!1}Z(){return!1}rW(){return!1}D(){return!1}};var B2m=class extends g.CR{constructor(t){super({W:"div",Jr:["ytp-upnext","ytp-player-content"],N:{"aria-label":"{{aria_label}}"},A:[{W:"div",B:"ytp-cued-thumbnail-overlay-image",N:{style:"{{background}}"}},{W:"span",B:"ytp-upnext-top",A:[{W:"span",B:"ytp-upnext-header",nx:"Up Next"},{W:"span",B:"ytp-upnext-title",nx:"{{title}}"},{W:"span",B:"ytp-upnext-author",nx:"{{author}}"}]},{W:"a",B:"ytp-upnext-autoplay-icon",N:{role:"button",href:"{{url}}","aria-label":"Play next video"},A:[{W:"svg",N:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},A:[{W:"circle",B:"ytp-svg-autoplay-circle",N:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{W:"circle",B:"ytp-svg-autoplay-ring",N:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{W:"path",B:"ytp-svg-fill",N:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{W:"span",B:"ytp-upnext-bottom",A:[{W:"span",B:"ytp-upnext-cancel"},
{W:"span",B:"ytp-upnext-paused",nx:"Auto-play is paused"}]}]});this.api=t;this.cancelButton=null;this.gm=this.wm("ytp-svg-autoplay-ring");this.V=this.notification=this.S=this.suggestion=null;this.Ph=new g.gq(this.C,5E3,this);this.Z=0;var p=this.wm("ytp-upnext-cancel");this.cancelButton=new g.CR({W:"button",Jr:["ytp-upnext-cancel-button","ytp-button"],N:{tabindex:"0","aria-label":"Cancel auto-play"},nx:"Cancel"});g.C(this,this.cancelButton);this.cancelButton.listen("click",this.IL,this);this.cancelButton.Wh(p);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.C(this,this.Ph);this.api.createClientVe(this.element,this,18788);p=this.wm("ytp-upnext-autoplay-icon");this.O(p,"click",this.EL);this.api.createClientVe(p,this,115130);this.Sv();this.O(t,"autonavvisibility",this.Sv);this.O(t,"mdxnowautoplaying",this.TH);this.O(t,"mdxautoplaycanceled",this.Kx);g.q3(this.element,"ytp-upnext-mobile",this.api.j().U)}C(){this.notification&&(this.Ph.stop(),this.uB(this.V),this.V=null,this.notification.close(),
this.notification=null)}D(t){this.suggestion=t;g.IQ(this,t,"hqdefault.jpg")}Sv(){this.Di(this.api.rW());this.api.logVisibility(this.element,this.api.rW());this.api.logVisibility(this.wm("ytp-upnext-autoplay-icon"),this.api.rW());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.rW())}sL(){window.focus();this.C()}L(t){this.X()||(g.KJ("a11y-announce",`Up Next ${this.suggestion.title}`),this.Z=(0,g.l)(),this.S=new g.gq(()=>{fT(this,t)},25),fT(this,t),xtZ(this.api,O5g(this,
t)));
g.x9(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}X(){return!!this.S}isCasting(){return this.api.getPresentingPlayerType()===3}K(){this.U();this.Z=(0,g.l)();fT(this);g.M3(this.element,"ytp-upnext-autoplay-paused")}U(){this.X()&&(this.S.dispose(),this.S=null)}select(t=!1){if(this.api.j().Y("autonav_notifications")&&t&&window.Notification&&typeof document.hasFocus==="function"){let p=Notification.permission;p==="default"?Notification.requestPermission():p!=="granted"||document.hasFocus()||
(this.C(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.rV()}),this.V=this.O(this.notification,"click",this.sL),this.Ph.start())}this.U();this.api.nextVideo(!1,t)}EL(t){!g.fj(this.cancelButton.element,t.target)&&g.u9(t,this.api)&&(this.api.rW()&&this.api.logClick(this.wm("ytp-upnext-autoplay-icon")),this.select())}IL(){this.api.rW()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.PV(this.api,!0)}TH(t){this.isCasting();this.show();
this.L(t)}Kx(){this.isCasting();this.U();this.hide()}qQ(){this.U();this.C();super.qQ()}};var Wxh=class extends zR{constructor(t){super(t,"videowall-endscreen");this.J=t;this.stills=[];this.U=this.videoData=null;this.K=this.V=!1;this.Ph=null;g.M3(this.element,"modern-videowall-endscreen");this.S=new g.u_(this);g.C(this,this.S);this.L=new g.gq(()=>{g.M3(this.element,"ytp-show-tiles")},0);
g.C(this,this.L);this.table=new g.dK({W:"div",B:"ytp-modern-endscreen-content"});g.C(this,this.table);this.table.Wh(this.element);t.getVideoData().Fd?this.X=new o9(t):this.X=new B2m(t);g.C(this,this.X);g.Ah(this.player,this.X.element,4);t.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var t=this.player.getVideoData();t&&(this.videoData=t);this.redraw();this.S.O(this.player,"appresize",this.redraw);this.S.O(this.player,"onVideoAreaChange",this.redraw);this.S.O(this.player,
"videodatachange",this.onVideoDataChange);this.S.O(this.player,"autonavchange",this.C);this.S.O(this.player,"onAutonavCancelled",this.Sv);t=this.videoData.autonavState;t!==this.Ph&&this.C(t,!1);this.S.O(this.element,"transitionend",this.IL)}destroy(){this.S.S();g.$6(this.stills);this.stills=[];super.destroy();g.x9(this.element,"ytp-show-tiles");this.L.stop();this.Ph=this.videoData.autonavState}Z(){return this.videoData?.It||this.videoData.autonavState!==1}show(){var t=this.W0;super.show();g.x9(this.element,
"ytp-show-tiles");this.player.j().U?g.dq(this.L):this.L.start();(this.K||this.U&&this.U!==this.videoData.clientPlaybackNonce)&&g.PV(this.player,!1);nT(this)?(R9(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||COm(this.player.o7())&&this.player.Y("web_player_pip_logging_fix")?this.X.select(!0):this.X.L():this.videoData.autonavState===3&&this.X.K()):(g.PV(this.player,!0),R9(this));t!==this.W0&&this.player.logVisibility(this.element,!0)}hide(){var t=this.W0;super.hide();this.X.K();
R9(this);t!==this.W0&&this.player.logVisibility(this.element,!1)}IL(t){t.target===this.element&&this.redraw()}redraw(){var t=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.V()];if(t.length){var p=this.J.IJ(!0,this.J.isFullscreen()),Q=Math.floor((p.width-64+16)/(g.jP(p.width*.27,250,450)+16));p=Math.min(3,Math.floor((p.height-64)/((p.width-64-(Q-1)*16)/Q*.5625+70)));g.CZ(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.M3(this.element,`ytp-modern-endscreen-limit-rows-${p}`);g.q3(this.element,"ytp-modern-endscreen-single-item",Q===1);g.q3(this.element,"ytp-modern-endscreen-row-0",p===0);Q=this.table.element;Q.ariaLive="polite";this.X.D(this.videoData.V());this.X instanceof o9&&this.X.redraw();g.q3(this.element,"ytp-endscreen-takeover",nT(this));R9(this);p=0;Q.ariaBusy="true";var e=t.length;for(let J=0;J<e;J++){let S=J%e,k=this.stills[J];k||(k=new g.FEz(this.player),this.stills[J]=k,Q.appendChild(k.element));g.ZW3(k,
t[S]);p++}this.stills.length=p}}onVideoDataChange(){var t=this.player.getVideoData({playerType:1});this.videoData!==t&&(t?.V()?(this.videoData=t,this.redraw()):this.player.XU("missg",{vid:t?.videoId||"",cpn:t?.clientPlaybackNonce||""}))}D(){return this.X.X()}C(t,p=!1){var Q=this.videoData?.It;if(t===1){if(!Q||p)this.K=!1,this.U=this.videoData.clientPlaybackNonce;this.X.U();this.W0&&this.redraw()}else this.K=!0,this.W0&&nT(this)&&(t===2?this.X.L():t===3&&this.X.K())}Sv(t){if(t){for(t=0;t<this.stills.length;t++)this.J.logVisibility(this.stills[t].element,
!0);this.C(1,!0)}else this.U=null,this.K=!1;this.redraw()}rW(){return this.W0&&nT(this)}};var POg=class extends g.CR{constructor(t){var p=t.j(),Q=g.QA||g.s0?{style:"will-change: opacity"}:void 0,e=p.K,J=["ytp-videowall-still"];p.U&&J.push("ytp-videowall-show-text");super({W:"a",Jr:J,N:{href:"{{url}}",target:e?p.Sv:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},A:[{W:"div",B:"ytp-videowall-still-image",N:{style:"{{background}}"}},{W:"span",B:"ytp-videowall-still-info",N:{"aria-hidden":"true"},A:[{W:"span",B:"ytp-videowall-still-info-bg",
A:[{W:"span",B:"ytp-videowall-still-info-content",N:Q,A:[{W:"span",B:"ytp-videowall-still-info-title",nx:"{{title}}"},{W:"span",B:"ytp-videowall-still-info-author",nx:"{{author_and_views}}"},{W:"span",B:"ytp-videowall-still-info-live",nx:"Live"},{W:"span",B:"ytp-videowall-still-info-duration",nx:"{{duration}}"}]}]}]},{W:"span",Jr:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],N:{"aria-hidden":"true"},A:[{W:"span",B:"ytp-videowall-still-listlabel-icon"},"Playlist",{W:"span",
B:"ytp-videowall-still-listlabel-length",A:[" (",{W:"span",nx:"{{playlist_length}}"},")"]}]},{W:"span",Jr:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],N:{"aria-hidden":"true"},A:[{W:"span",B:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{W:"span",B:"ytp-videowall-still-listlabel-length",nx:" (50+)"}]}]});this.suggestion=null;this.S=e;this.api=t;this.X=new g.u_(this);g.C(this,this.X);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.X.O(t,"videodatachange",
this.onVideoDataChange);t.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.qY(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Vk||void 0)&&this.api.logClick(this.element)}onClick(t){if(g.GY(this.api.j())&&this.api.Y("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let p=this.suggestion.KX(),Q={};g.hh(this.api,Q);p=g.Td(p,Q);g.oN(p,this.api,t)}else g.u9(t,this.api,
this.S,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(t){switch(t.keyCode){case 13:case 32:t.defaultPrevented||(this.select(),t.preventDefault())}}onVideoDataChange(){var t=this.api.getVideoData(),p=this.api.j();this.S=t.Tt?!1:p.K}};var H5X=class extends zR{constructor(t){super(t,"videowall-endscreen");this.J=t;this.U=0;this.stills=[];this.K=this.videoData=null;this.L=this.Ph=!1;this.Sv=null;this.S=new g.u_(this);g.C(this,this.S);this.C=new g.gq(()=>{g.M3(this.element,"ytp-show-tiles")},0);
g.C(this,this.C);var p=new g.CR({W:"button",Jr:["ytp-button","ytp-endscreen-previous"],N:{"aria-label":"Previous"},A:[g.kb()]});g.C(this,p);p.Wh(this.element);p.listen("click",this.gm,this);this.table=new g.dK({W:"div",B:"ytp-endscreen-content"});g.C(this,this.table);this.table.Wh(this.element);p=new g.CR({W:"button",Jr:["ytp-button","ytp-endscreen-next"],N:{"aria-label":"Next"},A:[g.wF()]});g.C(this,p);p.Wh(this.element);p.listen("click",this.EL,this);t.getVideoData().Fd?this.X=new o9(t):this.X=
new B2m(t);g.C(this,this.X);g.Ah(this.player,this.X.element,4);t.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var t=this.player.getVideoData();t&&(this.videoData=t);this.redraw();this.S.O(this.player,"appresize",this.redraw);this.S.O(this.player,"onVideoAreaChange",this.redraw);this.S.O(this.player,"videodatachange",this.onVideoDataChange);this.S.O(this.player,"autonavchange",this.V);this.S.O(this.player,"onAutonavCancelled",this.IL);t=this.videoData.autonavState;t!==
this.Sv&&this.V(t,!1);this.S.O(this.element,"transitionend",this.TH)}destroy(){this.S.S();g.$6(this.stills);this.stills=[];super.destroy();g.x9(this.element,"ytp-show-tiles");this.C.stop();this.Sv=this.videoData.autonavState}Z(){return this.videoData?.It||this.videoData?.autonavState!==1}show(){var t=this.W0;super.show();g.x9(this.element,"ytp-show-tiles");this.player.j().U?g.dq(this.C):this.C.start();(this.L||this.K&&this.K!==this.videoData.clientPlaybackNonce)&&g.PV(this.player,!1);N8(this)?(uF(this),
this.videoData.autonavState===2?this.player.getVisibilityState()===3||COm(this.player.o7())&&this.player.Y("web_player_pip_logging_fix")?this.X.select(!0):this.X.L():this.videoData.autonavState===3&&this.X.K()):(g.PV(this.player,!0),uF(this));t!==this.W0&&this.player.logVisibility(this.element,!0)}hide(){var t=this.W0;super.hide();this.X.K();uF(this);t!==this.W0&&this.player.logVisibility(this.element,!1)}TH(t){t.target===this.element&&this.redraw()}redraw(){var t=this.videoData?.suggestions?.length?
this.videoData?.suggestions:[this.videoData?.V()];if(t.length){g.M3(this.element,"ytp-endscreen-paginate");var p=this.J.IJ(!0,this.J.isFullscreen()),Q=g.qQ(this.J);Q&&(Q=Q.Ae()?48:32,p.width-=Q*2);var e=p.width/p.height,J=96/54,S=Q=2,k=Math.max(p.width/96,2),w=Math.max(p.height/54,2),f=t.length;var R=f*4;for(R-=4;R>0&&(Q<k||S<w);){var z=Q/2,y=S/2,X=Q<=k-2&&R>=y*4,E=S<=w-2&&R>=z*4;if((z+1)/y*J/e>e/(z/(y+1)*J)&&E)R-=z*4,S+=2;else if(X)R-=y*4,Q+=2;else if(E)R-=z*4,S+=2;else break}J=!1;R>=12&&f*4-R<=
6&&(S>=4||Q>=4)&&(J=!0);R=Q*96;k=S*54;e=R/k<e?p.height/k:p.width/R;e=Math.min(e,2);R=Math.floor(Math.min(p.width,R*e));k=Math.floor(Math.min(p.height,k*e));p=this.table.element;p.ariaLive="polite";g.HP(p,R,k);g.rI(p,{marginLeft:`${R/-2}px`,marginTop:`${k/-2}px`});this.X.D(this.videoData.V());this.X instanceof o9&&this.X.redraw();g.q3(this.element,"ytp-endscreen-takeover",N8(this));uF(this);R+=4;k+=4;e=0;p.ariaBusy="true";for(w=0;w<Q;w++)for(z=0;z<S;z++)if(X=e,E=0,J&&w>=Q-2&&z>=S-2?E=1:z%2===0&&w%
2===0&&(z<2&&w<2?z===0&&w===0&&(E=2):E=2),X=g.gr(X+this.U,f),E!==0){y=this.stills[e];y||(y=new POg(this.player),this.stills[e]=y,p.appendChild(y.element));var b=Math.floor(k*z/S);let M=Math.floor(R*w/Q),O=Math.floor(k*(z+E)/S)-b-4,Y=Math.floor(R*(w+E)/Q)-M-4;g.Ox(y.element,M,b);g.HP(y.element,Y,O);g.rI(y.element,"transitionDelay",(z+w)/20+"s");g.q3(y.element,"ytp-videowall-still-mini",E===1);g.q3(y.element,"ytp-videowall-still-large",E>2);E=Math.max(Y,O);g.q3(y.element,"ytp-videowall-still-round-large",
E>=256);g.q3(y.element,"ytp-videowall-still-round-medium",E>96&&E<256);g.q3(y.element,"ytp-videowall-still-round-small",E<=96);X=t[X];y.suggestion!==X&&(y.suggestion=X,E=y.api.j(),b=g.Z4(y.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.IQ(y,X,b),g.GY(E)&&!y.api.Y("web_player_log_click_before_generating_ve_conversion_params")&&(E=X.KX(),b={},g.MQ(y.api,"addEmbedsConversionTrackingParams",[b]),E=g.Td(E,b),y.updateValue("url",E)),(X=(X=X.sessionData)&&X.itct)&&y.api.setTrackingParams(y.element,
X));e++}p.ariaBusy="false";g.q3(this.element,"ytp-endscreen-paginate",e<f);for(t=this.stills.length-1;t>=e;t--)Q=this.stills[t],g.wI(Q.element),g.mH(Q);this.stills.length=e}}onVideoDataChange(){var t=this.player.getVideoData({playerType:1});this.videoData!==t&&(t?.V()?(this.U=0,this.videoData=t,this.redraw()):this.player.XU("missg",{vid:t?.videoId||"",cpn:t?.clientPlaybackNonce||""}))}EL(){this.U+=this.stills.length;this.redraw()}gm(){this.U-=this.stills.length;this.redraw()}D(){return this.X.X()}V(t,
p=!1){var Q=this.videoData?.It;if(t===1){if(!Q||p)this.L=!1,this.K=this.videoData.clientPlaybackNonce;this.X.U();this.W0&&this.redraw()}else this.L=!0,this.W0&&N8(this)&&(t===2?this.X.L():t===3&&this.X.K())}IL(t){if(t){for(t=0;t<this.stills.length;t++)this.J.logVisibility(this.stills[t].element,!0);this.V(1,!0)}else this.K=null,this.L=!1;this.redraw()}rW(){return this.W0&&N8(this)}};var Kx6=class extends g.CR{constructor(t){super({W:"button",Jr:["ytp-watch-on-youtube-button","ytp-button"],nx:"{{content}}"});this.J=t;this.buttonType=this.buttonType=1;this.X();this.buttonType===2&&g.M3(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.X);this.Di(!0)}X(){switch(this.buttonType){case 1:var t="Watch again on YouTube";var p=156915;break;case 2:t="Continue watching on YouTube";p=156942;break;default:t="Continue watching on YouTube",
p=156942}this.update({content:t});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,p)}onClick(t){this.J.Y("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.oN(this.getVideoUrl(),this.J,t);this.J.Y("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)}getVideoUrl(){var t=!0;switch(this.buttonType){case 1:t=!0;break;case 2:t=!1}t=this.J.getVideoUrl(t,!1,!1,!0);var p=
this.J.j();if(g.GY(p)){let Q={};g.GY(p)&&g.MQ(this.J,"addEmbedsConversionTrackingParams",[Q]);t=g.Td(t,Q)}return t}logVisibility(){this.J.logVisibility(this.element,this.W0&&this.bV)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}iB(t){super.iB(t);this.logVisibility()}};var l9O=class extends zR{constructor(t){super(t,"watch-again-on-youtube-endscreen");this.watchButton=new Kx6(t);g.C(this,this.watchButton);this.watchButton.Wh(this.element);g.VG5(t)&&(this.X=new g.xZm(t),g.C(this,this.X),this.S=new g.CR({W:"div",Jr:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],N:{tabIndex:"-1"},A:[this.X]}),g.C(this,this.S),this.X.Wh(this.S.element),this.S.Wh(this.element));t.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.X?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();let p=this.S;if(p){var t=this.X.hasSuggestions();g.q3(this.element,"ytp-shorts-branded-ui",t);t?p.show():p.hide()}g.qQ(this.player)?.xI(!0);this.player.logVisibility(this.element,!0);this.watchButton.iB(!0)}}hide(){super.hide();g.qQ(this.player)?.xI(!1);this.player.logVisibility(this.element,!1);this.watchButton.iB(!1)}};g.hQ("endscreen",class extends g.Cv{constructor(t){super(t);this.endScreen=null;this.X=this.S=!1;this.listeners=new g.u_(this);g.C(this,this.listeners);var p=t.j();t.isEmbedsShortsMode()?this.endScreen=new l9O(t):YYT(t)?(this.S=!0,a9T(this),p.Y("delhi_modern_endscreen")?this.endScreen=new Wxh(t):this.endScreen=new H5X(t)):this.endScreen=new zR(t);g.C(this,this.endScreen);g.Ah(t,this.endScreen.element,4);srf(this);this.listeners.O(t,"videodatachange",this.onVideoDataChange,this);this.listeners.O(t,
g.yP("endscreen"),Q=>{this.onCueRangeEnter(Q)});
this.listeners.O(t,g.mn("endscreen"),Q=>{this.onCueRangeExit(Q)})}LZ(){var t=this.player.getVideoData(),p=t.mutedAutoplay&&(t.limitedPlaybackDurationInSeconds>0||t.endSeconds>0||t.mutedAutoplayDurationMode!==2);
if(this.player.isEmbedsShortsMode()&&!p)return!0;var Q=!(!t.V()&&!t.suggestions?.length);Q=!YYT(this.player)||Q;var e=t.mV,J=this.player.HI();return(Q||!!t?.It)&&!e&&!J&&!p}rW(){return this.endScreen.rW()}Qv(){return this.rW()?this.endScreen.D():!1}qQ(){this.player.RI("endscreen");super.qQ()}load(){{let Q=this.player.getVideoData(),e=Q.transitionEndpointAtEndOfStream;if(e&&e.videoId){var t=this.player.QA().hI.get("heartbeat");var p=Q.V();!p||e.videoId!==p.videoId||Q.qs?(this.player.qY(e.videoId,void 0,
void 0,!0,!0,e),t&&t.Cj("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),t=!0):t=!1}else t=!1}t||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(t){this.LZ()&&(this.endScreen.created||this.endScreen.create(),t.getId()==="load"&&this.load())}onCueRangeExit(t){t.getId()==="load"&&this.loaded&&this.unload()}onVideoDataChange(){srf(this);this.S&&a9T(this)&&(this.endScreen&&
(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.endScreen=new H5X(this.player),g.C(this,this.endScreen),g.Ah(this.player,this.endScreen.element,4))}});})(_yt_player);
